opea-project/GenAIInfra

.github/license_template.txt, .github/pull_request_template.md, .github/workflows/code-scan.yml, .github/workflows/docker/code-scan.dockerfile, .github/workflows/docker/ut.dockerfile, .github/workflows/scripts/change_color, .github/workflows/scripts/codeScan/bandit.sh, .github/workflows/scripts/codeScan/hadolint.sh, .github/workflows/scripts/codeScan/trellix.sh, .github/workflows/scripts/test_ut.sh, .github/workflows/trellix.yml, .pre-commit-config.yaml, README.md, pyproject.toml
1. Support license template and auto apply license header. 
2. Support PR template.
3. Support code format scan and auto-fix with pre-commit.ci [Bot].
4. Support code security scan with Bandit/Hadolint/Dependabot/CodeQL/Trelli.
=> Add code scan CI 

manifests/DocSum/README.md, manifests/DocSum/manifests/backend-service.yaml, manifests/DocSum/manifests/inference-serving-tgi-gaudi.yaml, manifests/DocSum/manifests/inference-serving-tgi.yaml, manifests/DocSum/manifests/web-ui.yaml
feature: upload manifest files for deploy DocSum in Kubernetes
=> upload manifest files for deploy DocSum in Kubernetes

DEVELOPMENT.md, Makefile
Add DEVELOPMENT.md for developer guidance and Makefile for test
Makefile supports helm chart testing and pre-commit testing.
DEVELOPMENT.md has guidance to set up develop environment and do testing.
=> Add DEVELOPMENT.md for developer guidance and Makefile for test

.github/workflows/chart-validate.yaml
Add helm lint check in github workflow
Add helm lint check in github workflow
=> Add helm lint check in github workflow

README.md, helm-charts/README.md
Update document adding usages and helm-charts description
N/A
- [X ] Bug fix (non-breaking change which fixes an issue)
N/A
N/A
=> Update document adding usages and helm-charts description

helm-charts/codegen/templates/deployment.yaml
Codegen should use Release.Name to refer to tgi service.
Minor fix
=> Minor fix for the codegen

helm-charts/README.md, helm-charts/codegen/values.yaml
Improve helm-charts README
Improve helm-charts README to add chatqna service
n/a
n/a
=> Improve helm-charts README

manifests/ChatQnA/xeon/README.md, manifests/ChatQnA/xeon/chaqna-xeon-backend-server.yaml, manifests/ChatQnA/xeon/chaqna-xeon-ui-server.yaml, manifests/ChatQnA/xeon/embedding.yaml, manifests/ChatQnA/xeon/llm.yaml, manifests/ChatQnA/xeon/qna_configmap.yaml, manifests/ChatQnA/xeon/redis-vector-db.yaml, manifests/ChatQnA/xeon/reranking.yaml, manifests/ChatQnA/xeon/retriever.yaml, manifests/ChatQnA/xeon/tei_embedding_service.yaml, manifests/ChatQnA/xeon/tei_xeon_service.yaml, manifests/ChatQnA/xeon/tgi_service.yaml
upload the manifests files for deploy  ChatQnA in kubernetes cluster
The PR is related to this issue: https://github.com/opea-project/GenAIInfra/issues/4
- [x ] New feature (non-breaking change which adds new functionality)
tgi, tei,redis-vector-db
See the README.md
=> ChatQnA manifest files

.github/workflows/go-unittests.yaml
Enable go lint and unit test CI for microservices-connector
n/a
n/a
n/a
=> Enable go lint and unit test CI for microservices-connector

.github/workflows/chart-integration.yaml, .github/workflows/scripts/chart-integration/chart-test.sh, .github/workflows/scripts/chart-integration/lib.sh
Enable CI integration test for charts
n/a
n/a
n/a
=> Enable CI integration test for charts

manifests/CodeGen/xeon/README.md, manifests/CodeGen/xeon/codegen.yaml
Deploy the codegen by kubectl apply.
Add manifest to deploy with kubectl.
=> Add kubernetes manifest for CodeGen

.github/workflows/scripts/chart-integration/chart-test.sh, .github/workflows/scripts/chart-integration/lib.sh
Improve charts integration test ci by triggering codegen integration test
Improve charts integration test ci
n/a
n/a
=> Improve charts integration test ci

helm-charts/common/redis-vector-db/.helmignore, helm-charts/common/redis-vector-db/Chart.yaml, helm-charts/common/redis-vector-db/README.md, helm-charts/common/redis-vector-db/templates/NOTES.txt, helm-charts/common/redis-vector-db/templates/_helpers.tpl, helm-charts/common/redis-vector-db/templates/deployment.yaml, helm-charts/common/redis-vector-db/templates/service.yaml, helm-charts/common/redis-vector-db/values.yaml, helm-charts/common/tei/.helmignore, helm-charts/common/tei/Chart.yaml, helm-charts/common/tei/README.md, helm-charts/common/tei/templates/NOTES.txt, helm-charts/common/tei/templates/_helpers.tpl, helm-charts/common/tei/templates/deployment.yaml, helm-charts/common/tei/templates/service.yaml, helm-charts/common/tei/values.yaml
Upload common helmcharts : tei, redis-vector-db for ChatQnA
related to https://github.com/opea-project/GenAIInfra/issues/4
tei,redis-vector-db
Please see the README and notes of each helmchart
=> Upload common helmcharts: tei , redis-vector-db for ChatQnA

.github/workflows/manifest-validate.yaml, manifests/ChatQnA/xeon/README.md, manifests/ChatQnA/xeon/qna_configmap.yaml
Enable manifest validation in ci
n/a
n/a
n/a
=> Enable manifest validation in ci

manifests/ChatQnA/README.md, manifests/ChatQnA/chaqna-xeon-backend-server.yaml, manifests/ChatQnA/embedding.yaml, manifests/ChatQnA/llm.yaml, manifests/ChatQnA/qna_configmap_gaudi.yaml, manifests/ChatQnA/qna_configmap_xeon.yaml, manifests/ChatQnA/reranking.yaml, manifests/ChatQnA/retriever.yaml, manifests/ChatQnA/tei_embedding_gaudi_service.yaml, manifests/ChatQnA/tei_embedding_service.yaml, manifests/ChatQnA/tei_reranking_service.yaml, manifests/ChatQnA/tgi_gaudi_service.yaml, manifests/ChatQnA/tgi_service.yaml
Improve ChanQnA manifests, removing default namespace setting
n/a
n/a
n/a
=> Improve ChanQnA manifests

microservices-connector/templates/MicroChatQnA/gmc-manager.yaml
https://github.com/opea-project/GenAIInfra/issues/39
- [ x] Bug fix (non-breaking change which fixes an issue)
N/A
UT passed
=> change hostpath to configmap

.github/workflows/chart-e2e.yaml, .github/workflows/manifest-e2e.yaml, .github/workflows/scripts/e2e/manifest_test.sh
Add manifest integration test to CI
n/a
n/a
n/a
=> Add manifest integration test to CI

microservices-connector/config/samples/chatQnA_v2.yaml, microservices-connector/config/samples/codegen.yaml, microservices-connector/templates/MicroChatQnA/gmc-secret.yaml
https://github.com/opea-project/GenAIInfra/issues/54
- [x ] Bug fix (non-breaking change which fixes an issue)
=> remove token and proxy

.github/workflows/scripts/e2e/chart_test.sh
Support e2e test for chatqna helm chart
n/a
n/a
n/a
=> Support e2e test for chatqna helm chart

.github/workflows/chart-e2e.yaml, .github/workflows/manifest-e2e.yaml, .github/workflows/scripts/e2e/chart_test.sh, .github/workflows/scripts/e2e/manifest_test.sh
Enable new CI runner
n/a
n/a
n/a
=> Enable new CI runner

README.md
Add instructions of how to setup K8S in README
n/a
n/a
n/a
=> Add instructions of how to setup K8S in README

.github/workflows/scripts/e2e/chart_test.sh, .github/workflows/scripts/e2e/manifest_test.sh
Update codegen e2e test to verify result string
Closes #76 
n/a
CI test
=> Update codegen e2e test to verify result string

microservices-connector/cmd/router/main_test.go, microservices-connector/internal/controller/gmconnector_controller_test.go
add unit tests for router and controller
n/a
coverage up to 70%
=> GMC: add unit test

.github/workflows/scripts/e2e/manifest_gaudi_test.sh, .github/workflows/scripts/e2e/manifest_xeon_test.sh
Enable CI test for new workloads(DocSum, CodeTrans) on Gaudi
=> Enable CI test for new workloads on Gaudi

.github/workflows/go-e2e-gaudi.yaml, .github/workflows/scripts/e2e/gmc_test.sh
Enable GMC e2e on Gaudi
Partially closes issue #118 
N/A
CI Test
=> Enable GMC e2e on Gaudi

.github/workflows/chart-e2e.yaml, .github/workflows/scripts/e2e/chart_test.sh, .github/workflows/scripts/e2e/manifest_gaudi_test.sh, .github/workflows/scripts/e2e/manifest_xeon_test.sh, helm-charts/codegen/gaudi-values.yaml
Enable charts e2e on gaudi
Closes issue #120 
n/a
CI Tests
=> Enable charts e2e on gaudi

microservices-connector/README.md, microservices-connector/usage_guide.md
Update readme and user guide for GMC
`n/a`.
`n/a`.
`n/a`.
=> Update readme and user guide for GMC

.github/workflows/go-e2e-gaudi.yaml, .github/workflows/go-e2e.yaml, .github/workflows/scripts/e2e/gmc_gaudi_test.sh, .github/workflows/scripts/e2e/gmc_xeon_test.sh
1. Change the app namespapce from `chatqna-$(date +%Y%m%d%H%M%S)` to `opea-app-$(date +%Y%m%d%H%M%S)` to adapt different workloads instead of just chatqna.
2. Fix some typos in gmc e2e tests.
`n/a`
=> Optimize app namesapces and fix some typos in gmc e2e test.

.github/workflows/scripts/e2e/gmc_gaudi_test.sh, .github/workflows/scripts/e2e/gmc_xeon_test.sh
Improve the examples of `codegen` and `codetrans` e2e test.
There are something incorrect with the examples of `codegen` and `codetrans` e2e test.
`n/a`.
`n/a`.
**e2e for example of codegen**
**e2e for example of codetrans**
=> improve the examples of codegen and codetrans e2e test.

helm-charts/chatqna/Chart.yaml, helm-charts/common/data-prep/.helmignore, helm-charts/common/data-prep/Chart.yaml, helm-charts/common/data-prep/README.md, helm-charts/common/data-prep/templates/NOTES.txt, helm-charts/common/data-prep/templates/_helpers.tpl, helm-charts/common/data-prep/templates/deployment.yaml, helm-charts/common/data-prep/templates/service.yaml, helm-charts/common/data-prep/values.yaml, helm-charts/common/embedding-usvc/templates/deployment.yaml, helm-charts/common/embedding-usvc/templates/service.yaml, helm-charts/common/embedding-usvc/values.yaml, helm-charts/common/reranking-usvc/templates/deployment.yaml, helm-charts/common/reranking-usvc/templates/service.yaml, helm-charts/common/reranking-usvc/values.yaml, helm-charts/common/retriever-usvc/templates/service.yaml, helm-charts/common/retriever-usvc/values.yaml
=> Add dataprep common service

helm-charts/common/web-retriever/.helmignore, helm-charts/common/web-retriever/Chart.yaml, helm-charts/common/web-retriever/README.md, helm-charts/common/web-retriever/templates/_helpers.tpl, helm-charts/common/web-retriever/templates/deployment.yaml, helm-charts/common/web-retriever/templates/service.yaml, helm-charts/common/web-retriever/templates/tests/test-pod.yaml, helm-charts/common/web-retriever/values.yaml
This is the retriever component for example SearchQnA
Retriever component for example SearchQnA
=> Add web retriever component

.github/workflows/manifest-e2e.yaml, manifests/README.md, manifests/update_manifests.sh
Add script to generate yaml files from helm-charts
=> Add script to generate yaml files from helm-charts

helm-charts/common/asr/.helmignore, helm-charts/common/asr/Chart.yaml, helm-charts/common/asr/README.md, helm-charts/common/asr/templates/_helpers.tpl, helm-charts/common/asr/templates/configmap.yaml, helm-charts/common/asr/templates/deployment.yaml, helm-charts/common/asr/templates/service.yaml, helm-charts/common/asr/templates/tests/test-pod.yaml, helm-charts/common/asr/values.yaml, helm-charts/common/whisper/.helmignore, helm-charts/common/whisper/Chart.yaml, helm-charts/common/whisper/README.md, helm-charts/common/whisper/gaudi-values.yaml, helm-charts/common/whisper/templates/_helpers.tpl, helm-charts/common/whisper/templates/configmap.yaml, helm-charts/common/whisper/templates/deployment.yaml, helm-charts/common/whisper/templates/service.yaml, helm-charts/common/whisper/templates/tests/test-pod.yaml, helm-charts/common/whisper/values.yaml
Add whisper and asr components
=> Add whisper and asr components

helm-charts/common/speecht5/.helmignore, helm-charts/common/speecht5/Chart.yaml, helm-charts/common/speecht5/README.md, helm-charts/common/speecht5/gaudi-values.yaml, helm-charts/common/speecht5/templates/_helpers.tpl, helm-charts/common/speecht5/templates/configmap.yaml, helm-charts/common/speecht5/templates/deployment.yaml, helm-charts/common/speecht5/templates/service.yaml, helm-charts/common/speecht5/templates/tests/test-pod.yaml, helm-charts/common/speecht5/values.yaml, helm-charts/common/tts/.helmignore, helm-charts/common/tts/Chart.yaml, helm-charts/common/tts/README.md, helm-charts/common/tts/templates/_helpers.tpl, helm-charts/common/tts/templates/configmap.yaml, helm-charts/common/tts/templates/deployment.yaml, helm-charts/common/tts/templates/service.yaml, helm-charts/common/tts/templates/tests/test-pod.yaml, helm-charts/common/tts/values.yaml
Add tts and speecht5 components helm chart
=> Add tts and speecht5 components helm chart

.github/workflows/chart-e2e.yaml
Enable CI test for common components
=> CI for common

.github/workflows/chart-e2e.yaml
Disable the common component test for now for code refactor. Will enable it later.
=> Disable common component test

helm-charts/common/tei/templates/configmap.yaml, manifests/common/tei.yaml, manifests/common/tei_gaudi.yaml
update tei config for both xeon and gaudi
n/a
n/a
Manually tested on xeon and gaudi sw 1.16.2.
=> helm/manifest: update tei config for tei-gaudi

.github/workflows/chart-e2e.yaml, helm-charts/codetrans/.helmignore, helm-charts/codetrans/Chart.yaml, helm-charts/codetrans/README.md, helm-charts/codetrans/gaudi-values.yaml, helm-charts/codetrans/templates/_helpers.tpl, helm-charts/codetrans/templates/deployment.yaml, helm-charts/codetrans/templates/service.yaml, helm-charts/codetrans/templates/tests/test-pod.yaml, helm-charts/codetrans/values.yaml
=> Add CodeTrans helm chart

.github/workflows/chart-e2e.yaml, helm-charts/common/llm-uservice/templates/tests/test-pod.yaml, helm-charts/docsum/.helmignore, helm-charts/docsum/Chart.yaml, helm-charts/docsum/README.md, helm-charts/docsum/gaudi-values.yaml, helm-charts/docsum/templates/_helpers.tpl, helm-charts/docsum/templates/deployment.yaml, helm-charts/docsum/templates/service.yaml, helm-charts/docsum/templates/tests/test-pod.yaml, helm-charts/docsum/values.yaml
=> Add DocSum helm chart

.github/workflows/chart-e2e.yaml
Change tgi tag because gaudi driver is upgraded to 1.16.1
n/a
n/a
CI tests
=> Change tgi tag because gaudi driver is upgraded to 1.16.1

microservices-connector/internal/controller/gmconnector_controller.go
support multiple router service in one namespace
`n/a`.
- [X ] Bug fix (non-breaking change which fixes an issue)
manual test passed
=> support multiple router service in one namespace

.github/workflows/gmc-on-push.yaml, .github/workflows/go-e2e.yaml, .github/workflows/manifest-e2e.yaml
improve CI workflows trigger conditions to be more precise
n/a
n/a
CI tests
=> improve CI workflows trigger conditions to be more precise

microservices-connector/config/samples/translation_gaudi.yaml, microservices-connector/config/samples/translation_xeon.yaml
add translation example into GMC
curl http://router-service.translation.svc.cluster.local:8080   -X POST   -d '{"query":"Translate this from Chinese to English:\nChinese: 我爱机器翻译。\nEnglish:"}'   -H 'Content-Type: application/json'
data: b'I'
data: b' love'
data: b' machine'
data: b' translation'
data: b'.'
data: b'</s>'
data: [DONE]
=> add translation example into GMC

microservices-connector/README.md
add notes for replace hugging face token and mount directory path for models
`n/a`.
`n/a`.
`n/a`.
=> GMC: update README

.github/workflows/chart-e2e.yaml, .github/workflows/scripts/e2e/chart_test.sh
Improve chart e2e test workflow and scripts
n/a
n/a
CI tests
=> Improve chart e2e test workflow and scripts

.github/workflows/chart-e2e.yaml, .github/workflows/scripts/e2e/chart_test.sh
Enable google secrets in helm chart e2e workflow
n/a
n/a
CI tests
=> Enable google secrets in helm chart e2e workflow

.github/workflows/chart-e2e.yaml
Fix a bug of chart e2e workflow
n/a
n/a
CI verified
=> Fix a bug of chart e2e workflow

microservices-connector/internal/controller/gmconnector_controller.go
to fix the unsafe quoting error 
https://github.com/opea-project/GenAIInfra/security/code-scanning/6
'n/a'
=> GMC:  fix unsafe quoting

helm-charts/chatqna/gaudi-values.yaml, helm-charts/common/retriever-usvc/templates/deployment.yaml, helm-charts/common/retriever-usvc/templates/tests/test-pod.yaml, helm-charts/common/retriever-usvc/values.yaml, helm-charts/common/tgi/nv-values.yaml, manifests/common/retriever-usvc.yaml, manifests/common/tgi_nv.yaml
- Add K8S probes to retriever-usvc
- Align chatqna with GenAIExample on gaudi
- Remove redundant values in xx-values.yaml
issue #229
n/a.
=> helm: Add K8S probes to retriever-usvc

.github/workflows/gmc-helm.yaml, .github/workflows/gmc-on-push.yaml
Enable GMC helm installation test in CI
n/a
n/a
CI workflow template for GMC helm installation. Will be verified together with GMC helm PR.
=> Enable GMC helm installation test in CI

.github/workflows/gmc-helm.yaml, .github/workflows/go-unittests.yaml, .github/workflows/scripts/e2e/gmc_xeon_test.sh, .github/workflows/scripts/e2e/utils.sh, microservices-connector/README.md, microservices-connector/helm/.helmignore, microservices-connector/helm/Chart.yaml, microservices-connector/helm/README.md, microservices-connector/helm/crds/gmc.opea.io_gmconnectors.yaml, microservices-connector/helm/gmc-router.yaml, microservices-connector/helm/manifests_common, microservices-connector/helm/templates/NOTES.txt, microservices-connector/helm/templates/_helpers.tpl, microservices-connector/helm/templates/configmap.yaml, microservices-connector/helm/templates/deployment.yaml, microservices-connector/helm/templates/rbac.yaml, microservices-connector/helm/values.yaml
Add helm chart for deploying GMC itself.
issue #248 .
n/a.
=> Add helm chart for deploying GMC itself

.github/workflows/scripts/e2e/gmc_gaudi_test.sh, .github/workflows/scripts/e2e/gmc_xeon_test.sh
Add e2e test for chatQnA with dataprep microservice by supporting multiple endpoints
https://github.com/opea-project/GenAIInfra/issues/168
https://github.com/opea-project/GenAIInfra/issues/207
`n/a`.
This PR is for e2e test itself
=> Add e2e test for chatQnA with dataprep microservice

.github/workflows/chart-e2e.yaml
Add tag substitution for incominig helm PRs.
Related to issue #190
n/a.
=> CI: change chart e2e to support tag replacing

.github/workflows/image-build-on-manual.yaml
Enhance manually run image build workflow
n/a
n/a
CI workflow
=> Enhance manually run image build workflow

.github/workflows/image-build-on-manual.yaml, .github/workflows/scripts/e2e/gmc_install.sh
Fix errors in ci workflow
`n/a`
n/a
n/a
=> Fix errors in ci workflow

.github/workflows/scripts/e2e/gmc_gaudi_test.sh, .github/workflows/scripts/e2e/gmc_xeon_test.sh, microservices-connector/cmd/router/main.go
Change list:
1. Add e2e test for ChatQnA with switch mode enable
2. Fix the bug imported by output streaming support
`n/a`.
`n/a`.
This PR is e2e test itself.
=> Add e2e test for chatqna with switch mode enable

microservices-connector/helm/README.md
=> Fix typos in README

.github/workflows/_gmc-e2e.yaml, .github/workflows/_infra-workflow.yaml, .github/workflows/manual-cd-workflow.yaml, .github/workflows/pr-go-e2e.yaml, .github/workflows/scripts/e2e/gmc_install.sh
Set up CD workflow for GMC
n/a
n/a
CI tests
=> Set up CD workflow for GMC

microservices-connector/config/authN-authZ/README.md, microservices-connector/config/authN-authZ/oauth2_install.yaml
Some fix for authN and authZ with oauth2-proxy + OIDC
* remove plain-text cookie_secret from config file
* fix minor issues in doc
* remove redundant info in doc
- [*] Bug fix (non-breaking change which fixes an issue)
`n/a`
`n/a`
=> fix: update doc for authN-authZ with oauth

helm-charts/chatqna/gaudi-values.yaml, helm-charts/chatqna/nv-values.yaml, helm-charts/chatqna/values.yaml, helm-charts/codegen/gaudi-values.yaml, helm-charts/codegen/values.yaml, helm-charts/codetrans/gaudi-values.yaml, helm-charts/common/tgi/gaudi-values.yaml, helm-charts/common/tgi/nv-values.yaml, helm-charts/common/tgi/templates/configmap.yaml, helm-charts/common/tgi/values.yaml, helm-charts/docsum/gaudi-values.yaml, microservices-connector/config/manifests/tgi.yaml, microservices-connector/config/samples/codegen_gaudi.yaml, microservices-connector/config/samples/codegen_xeon.yaml
=> tgi: Update tgi version on xeon to latest-intel-cpu

helm-charts/chatqna/README.md, helm-charts/common/chatqna-ui/templates/configmap.yaml
* update the chatqna helm chart readme to provide the steps for UI-based verification
* update the env name according to changes in GenAIExamples
#254 
`n/a`
`n/a`
=> ui: update chatqna helm chart readme and env name

.github/workflows/manual-freeze-tag.yml, .github/workflows/push-image-build.yaml
Add manual job to freeze image tags and versions
n/a
n/a
n/a
=> Add manual job to freeze image tags and versions after code freeze

microservices-connector/README.md, microservices-connector/api/v1alpha3/validating_webhook.go, microservices-connector/api/v1alpha3/validating_webhook_test.go, microservices-connector/troubleshooting_guide.md
1. Add troubleshooting guide for identifying CR issues
2. Correct the json path in validating errors
3. Add TgiNvidia to the stepName list
n/a
n/a
The unit test has been updated accordingly.
=> Troubleshooting guide for the validating webhook.

helm-charts/common/tgi/nv-values.yaml, microservices-connector/config/manifests/tgi_nv.yaml
Correct TGI image tag for NV platform
N/A
=> Correct TGI image tag for NV platform

.github/workflows/manual-helm-cd-workflow.yaml
fix errors of manual helm test workflow
n/a
n/a
n/a
=> fix errors of manual helm test workflow

.github/workflows/_gmc-image-build.yaml, .github/workflows/_helm-e2e.yaml, .github/workflows/_infra-workflow.yaml, .github/workflows/manual-gmc-cd-workflow.yaml, .github/workflows/manual-helm-cd-workflow.yaml, RELEASE_BRANCHES.md
improve cd workflows, add release document
n/a
n/a
n/a
=> improve cd workflows and add release document

.github/workflows/push-image-build.yaml
Enable gmc build workflow on push
n/a
n/a
n/a
=> Enable gmc build workflow on push

microservices-connector/README.md, microservices-connector/config/samples/ChatQnA/chatQnA_switch_gaudi.yaml, microservices-connector/config/samples/ChatQnA/chatQnA_switch_xeon.yaml, microservices-connector/config/samples/ChatQnA/use_cases.md
Change list:
1. Add all 3 use cases of ChatQnA examples
2. Add reference link in GMC README
3. change the switch case models to `openlm-research/open_llama_3b`
`n/a`.
`n/a`.
This change contains doc and yaml file which can trigger automatically e2e test.
=> Add docs for all 3 use cases of ChatQnA examples and change models for switch case

microservices-connector/helm/Chart.yaml, microservices-connector/usage_guide.md, scripts/nvidia/README.md, scripts/nvidia/gmc-chatqna-pipeline.sh
Fix some typos to run GMC more smoothly
=> Doc: Fix some typos to run GMC more smoothly

.github/workflows/_helm-e2e.yaml, .github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
Enable guardrail case in helm e2e tests
n/a
n/a
CI tests
=> Enable guardrail case in helm e2e tests

.github/workflows/scripts/e2e/gmc_xeon_test.sh
fix a bad commit in #383 
#383
n/a
=>  fix a badcommit in #383

microservices-connector/config/samples/ChatQnA/chatQnA_dataprep_nv.yaml
Add dataprep CR for NV platform
https://github.com/opea-project/GenAIInfra/issues/323
=> Add dataprep CR for NV platform

.github/workflows/pr-go-unittests.yaml
Enable unit test for memory-bandwidth-exporter in CI
n/a
n/a
CI test passes
=> Enable unit test for memory-bandwidth-exporter in CI

helm-charts/common/vllm/.helmignore, helm-charts/common/vllm/Chart.yaml, helm-charts/common/vllm/README.md, helm-charts/common/vllm/gaudi-values.yaml, helm-charts/common/vllm/templates/_helpers.tpl, helm-charts/common/vllm/templates/configmap.yaml, helm-charts/common/vllm/templates/deployment.yaml, helm-charts/common/vllm/templates/service.yaml, helm-charts/common/vllm/templates/tests/test-pod.yaml, helm-charts/common/vllm/values.yaml
Add helm chart support for component vllm
https://github.com/opea-project/GenAIComps/tree/main/comps/llms/text-generation/vllm
=> Add vLLM inference engine support

README.md, helm-charts/common/asr/README.md, helm-charts/common/data-prep/README.md, helm-charts/common/embedding-usvc/README.md, helm-charts/common/guardrails-usvc/README.md, helm-charts/common/llm-uservice/README.md, helm-charts/common/reranking-usvc/README.md, helm-charts/common/retriever-usvc/README.md, helm-charts/common/tts/README.md, helm-charts/common/web-retriever/README.md, microservices-connector/README.md, microservices-connector/config/samples/ChatQnA/use_cases.md, microservices-connector/troubleshooting_guide.md
* remove trailing punctuation on headings
* fix indenting within lists
* catch some misspellings and remove use of please
=> doc: fix headings and indenting

.github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
disable hpa-values test in chart e2e in CI
n/a
n/a
n/a
=> disable hpa-values test in chart e2e in CI

.github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
Skip nv-values.yaml and hpa-values.yaml since our current CI infra doesn't support testing them.
#417 .
=> Fix CI bug #417

kubernetes-addons/Observability/README.md, kubernetes-addons/memory-bandwidth-exporter/README.md
* heading levels should not skip a level
* don't put leading $ on commands (prevents copy/paste)
* don't put : at end of headings:
=> doc: fix markdown issues

microservices-connector/config/samples/ChatQnA/use_cases.md
Update the image version for ChatQnA examples
`n/a`.
`n/a`.
`n/a`.
=> Update the image version for ChatQnA examples

helm-charts/README.md
=> Enhance helm chart repo usage in README

.github/workflows/_mbe-image-build.yaml, .github/workflows/push-gmc-image-build.yaml, .github/workflows/push-mbe-image-build.yaml
enable image build process for memory-bandwidth-exporter
n/a
n/a
tested by CI: https://github.com/opea-project/GenAIInfra/actions/runs/10989121268/job/30506714011
=> enable image build process for memory-bandwidth-exporter

kubernetes-addons/memory-bandwidth-exporter/plugin/hook-injector.go
Fix the conflict between memory bandwidth exporter and habana device plugin.
n/a
n/a
n/a
n/a
=> Fix the conflict between memory bandwidth exporter and habana device plugin.

helm-charts/chatqna/ci-guardrails-values.yaml, helm-charts/common/guardrails-usvc/values.yaml, helm-charts/common/llm-uservice/variant_docsum-values.yaml, helm-charts/common/llm-uservice/variant_faqgen-values.yaml, helm-charts/common/prompt-usvc/values.yaml, helm-charts/common/retriever-usvc/ci-values.yaml
Set proper dependency for retriever-usvc.
Modify prompt-usvc port to 6018.
Fix guardrail tgi setting.
Removed ci test for chatqna-guardrails.
=> Fix previous CI failures

.github/workflows/pr-path-detection.yml
=> Fix link check failure

helm-charts/README.md
Helm charts README improvements:
- Simplify unnecessary complicated clauses
- Add missing spaces & remove trailing ones
- Consistently use fixed font for file names
- Correctly uppercase Docker, Helm, HuggingFace, Kubernetes and YAML
`n/a`
`n/a`
`n/a`
=> Improve Helm charts README

helm-charts/chatqna/templates/deployment.yaml
Adapt chatqna due to chatqna megaservice changes:
- https://github.com/opea-project/GenAIExamples/pull/977
- https://github.com/opea-project/GenAIExamples/pull/984
- issue #484 
- issue #491
n/a.
=> helm: Adapt chatqna due to chatqna megaservice changes

helm-charts/chatqna/templates/nginx-deployment.yaml, helm-charts/chatqna/values.yaml, helm-charts/codegen/templates/nginx-deployment.yaml, helm-charts/codegen/values.yaml, helm-charts/codetrans/templates/nginx-deployment.yaml, helm-charts/codetrans/values.yaml, helm-charts/common/ui/templates/tests/test-pod.yaml, helm-charts/docsum/templates/nginx-deployment.yaml, helm-charts/docsum/templates/tests/test-pod.yaml, helm-charts/docsum/values.yaml
- helm-chart: Make nginx service type configurable
- helm-chart: change docsum and ui test-pod due to latest changes
#501
=> helm-chart: Make nginx service type configurable

helm-charts/codegen/README.md, helm-charts/codegen/values.yaml, helm-charts/codetrans/README.md, helm-charts/codetrans/values.yaml, microservices-connector/config/samples/CodeGen/codegen_gaudi.yaml, microservices-connector/config/samples/CodeGen/codegen_xeon.yaml, microservices-connector/config/samples/CodeTrans/codetrans_gaudi.yaml, microservices-connector/config/samples/CodeTrans/codetrans_xeon.yaml
Change default model of codegen and codetrans.
#503
=> Change default model of codegen and codetrans

helm-charts/audioqna/.helmignore, helm-charts/audioqna/Chart.yaml, helm-charts/audioqna/README.md, helm-charts/audioqna/ci-gaudi-values.yaml, helm-charts/audioqna/ci-values.yaml, helm-charts/audioqna/gaudi-values.yaml, helm-charts/audioqna/templates/_helpers.tpl, helm-charts/audioqna/templates/deployment.yaml, helm-charts/audioqna/templates/nginx-deployment.yaml, helm-charts/audioqna/templates/service.yaml, helm-charts/audioqna/templates/tests/test-pod.yaml, helm-charts/audioqna/values.yaml
Add audioQnA e2e helm chart.
#504
n/a.
CI.
=> helm: Add audioQnA e2e helm chart

helm-charts/faqgen/.helmignore, helm-charts/faqgen/Chart.yaml, helm-charts/faqgen/README.md, helm-charts/faqgen/ci-gaudi-values.yaml, helm-charts/faqgen/ci-values.yaml, helm-charts/faqgen/gaudi-values.yaml, helm-charts/faqgen/templates/_helpers.tpl, helm-charts/faqgen/templates/deployment.yaml, helm-charts/faqgen/templates/nginx-deployment.yaml, helm-charts/faqgen/templates/service.yaml, helm-charts/faqgen/templates/tests/test-pod.yaml, helm-charts/faqgen/values.yaml
Add FaqGen helm chart
#504 
helm test faqgen
=> Add FaqGen helm chart

helm-charts/common/tgi/values.yaml, microservices-connector/config/manifests/tgi.yaml
Update tgi cpu image version to 2.4.0-intel-cpu
#522 
=> Update tgi cpu image version to 2.4.0-intel-cpu

helm-charts/agentqna/gaudi-values.yaml, helm-charts/audioqna/gaudi-values.yaml, helm-charts/chatqna/gaudi-values.yaml, helm-charts/chatqna/guardrails-gaudi-values.yaml, helm-charts/codegen/gaudi-values.yaml, helm-charts/codetrans/gaudi-values.yaml, helm-charts/common/agent/gaudi-values.yaml, helm-charts/common/tgi/gaudi-values.yaml, helm-charts/docsum/gaudi-values.yaml, helm-charts/faqgen/README.md, helm-charts/faqgen/gaudi-values.yaml, helm-charts/faqgen/templates/tests/test-pod.yaml, helm-charts/visualqna/gaudi-values.yaml, microservices-connector/config/manifests/tgi_gaudi.yaml, microservices-connector/config/samples/ChatQnA/use_cases.md
Upgrade tgi-gaudi to version 2.0.6.
#549.
=> Upgrade tgi-gaudi to version 2.0.6

helm-charts/common/ui/templates/configmap.yaml, helm-charts/common/ui/values.yaml
Update the env of FaqGen Svelte UI according to the change here https://github.com/opea-project/GenAIExamples/commit/73879d3cecbd91bb7b66e45f0561f27e2803c8c6#diff-caa85520f73ef6af57dc0418b2e673f4f2333655aa6ced6fd8ad72ba5e61ecd6R25
#558 
`n/a`
CI tests
=> helm-chart: update faq svelte ui env

helm-charts/common/tgi/templates/configmap.yaml, helm-charts/common/vllm/templates/configmap.yaml, microservices-connector/config/manifests/tgi.yaml, microservices-connector/config/manifests/tgi_nv.yaml, microservices-connector/config/manifests/vllm.yaml
Only set HABANA_LOGS env in gaudi case.
`n/a`.
=> Only set HABANA_LOGS env in gaudi case

helm-charts/audioqna/README.md, helm-charts/visualqna/templates/deployment.yaml
- visualqna: Pass proxy settings into pod
- audioqna: change README wording
#591 
=> Fix VisualQnA & AudioQnA

.github/workflows/manual-helm-cd-workflow.yaml
Helm CD workflow fixes by
commit 0ff87d75478937bea0ce90d4caa3e071519df057
commit 5568a08c17b2f6fbe8e08124d1de6513a9d7b6cd
=> Sync GH Action changes from v1.1rc branch

helm-charts/audioqna/templates/nginx-deployment.yaml, helm-charts/chatqna/templates/nginx-deployment.yaml, helm-charts/codegen/templates/nginx-deployment.yaml, helm-charts/codetrans/templates/nginx-deployment.yaml, helm-charts/docsum/templates/nginx-deployment.yaml, helm-charts/faqgen/templates/nginx-deployment.yaml, helm-charts/visualqna/templates/nginx-deployment.yaml
* change the nginx configuration
* switch the default ChatQnA UI image to svelte version
#589 
`n\a`
`n\a`
=> helm-chart: update nginx config and minor changes

.github/workflows/pr-chart-validate.yaml
Add milvus repo to fix the helm dep build issue.
=> Fix ct lint

helm-charts/chatqna/guardrails-gaudi-values.yaml, helm-charts/chatqna/guardrails-values.yaml, helm-charts/common/guardrails-usvc/Chart.yaml, helm-charts/common/guardrails-usvc/README.md, helm-charts/common/guardrails-usvc/ci-values.yaml, helm-charts/common/guardrails-usvc/templates/configmap.yaml, helm-charts/common/guardrails-usvc/values.yaml
Use alias tgi-guardrails consistently so we can spell the correct name.
Fixed #614 
Manual tested on proxy env.
=> Fix guardrails-usvc no_proxy settings

.github/ISSUE_TEMPLATE/1_bug_template.yml, .github/ISSUE_TEMPLATE/2_feature_template.yml, .github/ISSUE_TEMPLATE/config.yml
=> add label automatically when create issue

.github/workflows/scripts/e2e/chart_test.sh
Dump all containers' log for chart test.
`n/a`.
=> CI: dump all containers' log for chart test

helm-charts/chatqna/Chart.yaml, helm-charts/chatqna/guardrails-gaudi-values.yaml, helm-charts/chatqna/guardrails-values.yaml, helm-charts/chatqna/norerank-values.yaml, helm-charts/chatqna/templates/deployment.yaml, helm-charts/chatqna/values.yaml, helm-charts/chatqna/withwrapper-values.yaml
#608 
Manually test with -f
gaudi-tgi-values.yaml gaudi-vllm-values.yaml guardrails-values.yaml guardrails-gaudi-values.yaml withwrapper-values.yaml norerank-values.yaml
=> Make chatqna components configurable

.github/license_template.txt
Change license template 2024 to 2025
=> Change license template from 2024 to 2025

.github/workflows/pr-path-detection.yml
=> Optimize output prompt words

.github/workflows/releasedevhelm.yaml
=> Use pull_request_target event to access secrets

helm-charts/common/reranking-usvc/.helmignore, helm-charts/common/reranking-usvc/README.md, helm-charts/common/reranking-usvc/templates/configmap.yaml, helm-charts/common/reranking-usvc/templates/deployment.yaml, helm-charts/common/reranking-usvc/templates/tests/test-pod.yaml, helm-charts/common/reranking-usvc/values.yaml, helm-charts/common/web-retriever/.helmignore, helm-charts/common/web-retriever/templates/deployment.yaml, helm-charts/common/web-retriever/values.yaml
Adapt rerank/web-retriever to latest changes
`n/a`.
=> Adapt rerank/web-retriever to latest changes

helm-charts/common/asr/.helmignore, helm-charts/common/asr/README.md, helm-charts/common/asr/templates/deployment.yaml, helm-charts/common/asr/templates/tests/test-pod.yaml, helm-charts/common/asr/values.yaml, helm-charts/common/gpt-sovits/.helmignore, helm-charts/common/gpt-sovits/templates/deployment.yaml, helm-charts/common/gpt-sovits/values.yaml, helm-charts/common/speecht5/.helmignore, helm-charts/common/speecht5/templates/deployment.yaml, helm-charts/common/speecht5/values.yaml, helm-charts/common/tts/.helmignore, helm-charts/common/tts/README.md, helm-charts/common/tts/templates/deployment.yaml, helm-charts/common/tts/templates/tests/test-pod.yaml, helm-charts/common/tts/values.yaml, helm-charts/common/whisper/.helmignore, helm-charts/common/whisper/templates/deployment.yaml, helm-charts/common/whisper/values.yaml
Adapt the latest changes in helm charts of the following components:
- asr
- whisper
- tts
- speecht5
- gpt-sovits
`n/a`.
CI.
=> Adapt latest changes in asr/tts related components

helm-charts/common/text2image/.helmignore, helm-charts/common/text2image/Chart.yaml, helm-charts/common/text2image/README.md, helm-charts/common/text2image/ci-gaudi-values.yaml, helm-charts/common/text2image/ci-values.yaml, helm-charts/common/text2image/gaudi-values.yaml, helm-charts/common/text2image/templates/_helpers.tpl, helm-charts/common/text2image/templates/configmap.yaml, helm-charts/common/text2image/templates/deployment.yaml, helm-charts/common/text2image/templates/horizontal-pod-autoscaler.yaml, helm-charts/common/text2image/templates/service.yaml, helm-charts/common/text2image/templates/serviceaccount.yaml, helm-charts/common/text2image/templates/servicemonitor.yaml, helm-charts/common/text2image/templates/tests/test-pod.yaml, helm-charts/common/text2image/values.yaml
Add text2image microservice support.
Part of issue #596 
=> Add text2image microservice support

README.md, kubernetes-addons/Intel-Gaudi-Base-Operator/README.md
cleanup: remove unused directory
`n/a`.
`n/a`.
`n/a`.
=> Remove unused directory

.github/workflows/push-release-charts.yaml
Push event don't use type, delete it.
=> Fix ci script

.github/workflows/_helm-e2e.yaml, .github/workflows/scripts/e2e/chart_test.sh
Check local images' availability before helm e2e test. Fail tests with no available images early to save test time..
`n/a`.
=> CI: check local image availability

helm-charts/common/ui/templates/configmap.yaml, helm-charts/searchqna/.helmignore, helm-charts/searchqna/Chart.yaml, helm-charts/searchqna/README.md, helm-charts/searchqna/cpu-values.yaml, helm-charts/searchqna/gaudi-values.yaml, helm-charts/searchqna/templates/_helpers.tpl, helm-charts/searchqna/templates/deployment.yaml, helm-charts/searchqna/templates/nginx.yaml, helm-charts/searchqna/templates/service.yaml, helm-charts/searchqna/templates/serviceaccount.yaml, helm-charts/searchqna/templates/servicemonitor.yaml, helm-charts/searchqna/templates/tests/test-pod.yaml, helm-charts/searchqna/values.yaml
Add SearchQnA e2e helm chart.
Part of issue #596.
=> Add SearchQnA e2e helm chart

helm-charts/common/ui/templates/configmap.yaml, helm-charts/txt2img/.helmignore, helm-charts/txt2img/Chart.yaml, helm-charts/txt2img/README.md, helm-charts/txt2img/cpu-values.yaml, helm-charts/txt2img/gaudi-values.yaml, helm-charts/txt2img/templates/_helpers.tpl, helm-charts/txt2img/templates/nginx.yaml, helm-charts/txt2img/templates/serviceaccount.yaml, helm-charts/txt2img/templates/tests/test-pod.yaml, helm-charts/txt2img/values.yaml, helm-charts/valuefiles.yaml
There is no mega service for text2image, just add an options to the components.
Part of #596 
=> Add Text2Image e2e helm chart

helm-charts/common/embedding-usvc/templates/deployment.yaml, helm-charts/common/guardrails-usvc/templates/deployment.yaml, helm-charts/common/llm-uservice/templates/deployment.yaml, helm-charts/common/lvm-uservice/templates/deployment.yaml, helm-charts/common/retriever-usvc/templates/deployment.yaml
Improve wait logic to be more time precise in the following component chart:
- embeding-usvc
- guardrails-usvc
- llm-uservice
- lvm-uservice
- retriever-usvc
`n/a`.
=> Improve wait logic

.github/workflows/push-release-charts.yaml, helm-charts/agentqna/Chart.yaml, helm-charts/agentqna/templates/nginx.yaml, helm-charts/agentqna/templates/tests/test-pod.yaml, helm-charts/agentqna/values.yaml, helm-charts/common/agent/templates/configmap.yaml, helm-charts/common/agent/templates/tests/test-pod.yaml, helm-charts/common/ui/templates/configmap.yaml, helm-charts/common/ui/variant_agentqna_svelte-values.yaml
Add AgentQnA UI support, and fix 2 issues.
Follow up with https://github.com/opea-project/GenAIExamples/pull/1389
=> Add AgentQnA UI

helm-charts/agentqna/values.yaml, helm-charts/audioqna/gaudi-values.yaml, helm-charts/codegen/gaudi-values.yaml, helm-charts/codetrans/gaudi-values.yaml, helm-charts/common/agent/gaudi-values.yaml, helm-charts/common/tgi/gaudi-values.yaml, helm-charts/common/tgi/templates/configmap.yaml, helm-charts/docsum/gaudi-values.yaml, helm-charts/faqgen/gaudi-values.yaml, helm-charts/searchqna/gaudi-values.yaml, helm-charts/visualqna/gaudi-values.yaml
Upgrade tgi-gaudi verion to 2.3.1.
Fixes #729
=> Upgrade tgi-gaudi verion to 2.3.1

.github/workflows/_helm-e2e.yaml
Increase CI wait time for vllm-gaudi because vllm-gaudi takes more time to warm up models during startup.
`n/a`.
=> CI: increase wait time for vllm-gaudi

helm-charts/common/lvm-serve/gaudi-values.yaml, helm-charts/common/lvm-serve/variant_llama-vision-guard-values.yaml, helm-charts/common/lvm-serve/variant_llama-vision-tp-values.yaml, helm-charts/common/lvm-serve/variant_llama-vision-values.yaml, helm-charts/common/lvm-serve/variant_video-llama-values.yaml, helm-charts/common/mm-embedding/gaudi-values.yaml, helm-charts/common/mm-embedding/variant_clip-values.yaml, helm-charts/common/text2image/gaudi-values.yaml, helm-charts/txt2img/gaudi-values.yaml, helm-charts/valuefiles.yaml
The latest tag is specified in the default values.yaml.
Add mm-embedding in valuefiles.yaml to track sync status with GenAIComps.
=> Remove latest tag in value files

helm-charts/common/redis-vector-db/templates/tests/test-pod.yaml
Improve redis test for retry in case of k8s service is not ready in time.
`n/a`.
=> redis: improve redis test

.github/workflows/_helm-e2e.yaml
Fix CI: use lowercase in namespace
`n/a`.
=> Fix CI: use lowercase in namespace

helm-charts/common/lvm-uservice/templates/configmap.yaml, helm-charts/common/lvm-uservice/values.yaml
Adapt to config changes of lvm source code.
Fixes #754
=> lvm-uservice: adapt to config changes

.github/workflows/manual-helm-cd-workflow.yaml
Fix helm CD to pick up the right test value files.
`n/a`.
=> Fix helm CD to pick up the right test value files

.github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml, .github/workflows/pr-chart-validate.yaml
CI: enable mivlus related test
`n/a`.
=> CI: enable mivlus related test

DEVELOPMENT.md, dev/README.md, dev/helm-chart-starter/.helmignore, dev/helm-chart-starter/Chart.yaml, dev/helm-chart-starter/README.md, dev/helm-chart-starter/cpu-values.yaml, dev/helm-chart-starter/templates/NOTES.txt, dev/helm-chart-starter/templates/_helpers.tpl, dev/helm-chart-starter/templates/configmap.yaml, dev/helm-chart-starter/templates/deployment.yaml, dev/helm-chart-starter/templates/horizontal-pod-autoscaler.yaml, dev/helm-chart-starter/templates/ingress.yaml, dev/helm-chart-starter/templates/service.yaml, dev/helm-chart-starter/templates/serviceaccount.yaml, dev/helm-chart-starter/templates/servicemonitor.yaml, dev/helm-chart-starter/templates/tests/test-pod.yaml, dev/helm-chart-starter/values.yaml
Add helm starter chart for developing new charts.
`n/a`.
n/a.
n/a.
=> Add helm starter chart for developing new charts

helm-charts/common/data-prep/Chart.yaml, helm-charts/common/data-prep/README.md, helm-charts/common/data-prep/qdrant-values.yaml, helm-charts/common/data-prep/templates/configmap.yaml, helm-charts/common/data-prep/templates/deployment.yaml, helm-charts/common/data-prep/values.yaml, helm-charts/common/retriever-usvc/Chart.yaml, helm-charts/common/retriever-usvc/README.md, helm-charts/common/retriever-usvc/qdrant-values.yaml, helm-charts/common/retriever-usvc/templates/configmap.yaml, helm-charts/common/retriever-usvc/templates/deployment.yaml, helm-charts/common/retriever-usvc/values.yaml
Add Qdrant support in the following charts:
- data-prep
- retriever
Part of issue #706.
=> Helm: Add Qdrant support

helm-charts/chatqna/Chart.yaml, helm-charts/chatqna/README.md, helm-charts/chatqna/cpu-qdrant-values.yaml, helm-charts/chatqna/values.yaml, helm-charts/valuefiles.yaml
Add Qdrant DB support support in chatqna.
Part of issue #706
=> Chatqna: Add Qdrant DB support

helm-charts/common/data-prep/templates/configmap.yaml, helm-charts/common/data-prep/templates/deployment.yaml, helm-charts/common/data-prep/templates/tests/test-pod.yaml, helm-charts/common/data-prep/values.yaml, helm-charts/common/retriever-usvc/templates/configmap.yaml, helm-charts/common/retriever-usvc/templates/deployment.yaml, helm-charts/common/retriever-usvc/values.yaml
Add readOnlyRootFileSystem for dataprep and retriever.
Part of #815.
=> Add readOnlyRootFileSystem for dataprep and retriever

.github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
=> Temporarily disable Gaudi test

.github/workflows/daily_check_issue_and_pr.yml
Add GitHub Action to check and close stale issues and PRs
`n/a`
=> Add GitHub Action to check and close stale issues and PRs

helm-charts/common/chathistory-usvc/values.yaml, helm-charts/common/lvm-uservice/values.yaml, helm-charts/common/nginx/values.yaml, helm-charts/common/prompt-usvc/values.yaml, helm-charts/common/text2image/values.yaml, helm-charts/valuefiles.yaml
More security hardening for the following common helm charts:
- nginx
- chathistory-usvc
- lvm-uservice
- prompt-usvc
- text2image
Part of issue #815 
=> More security hardening for common helm charts

.github/workflows/_helm-e2e.yaml, .github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
Enable CI for Gaudi on new CI servers and cleanup some of the test scripts.
=> Enable new ci

helm-charts/audioqna/Chart.yaml, helm-charts/audioqna/README.md, helm-charts/audioqna/cpu-multilang-values.yaml, helm-charts/audioqna/cpu-tgi-values.yaml, helm-charts/audioqna/gaudi-tgi-values.yaml, helm-charts/audioqna/gaudi-values.yaml, helm-charts/audioqna/templates/deployment.yaml, helm-charts/audioqna/values.yaml, helm-charts/valuefiles.yaml
Adapt latest changes of audioqna:
- add vLLM as default inference engine
- change default model
- add multilang support
Fixes #873
CI for cpu env, manually test for gaudi env.
=> Adapt latest changes of audioqna

.github/workflows/_helm-e2e.yaml, .github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
Enable Gaudi test on new CI servers.
Use secret for HF_TOKEN.
Manually trigger CI, passed except for a few lacking of docker images.
https://github.com/opea-project/GenAIInfra/actions/runs/13987958404
=> Revert Temporarily disable Gaudi test and clean up test scripts. (#889)

.github/workflows/manual-helm-cd-workflow.yaml
Cron triggered job does not allow inputs. Using || 'default' value.
Put in a branch first for test.
=> Trigger helm test every Saturday

.github/workflows/_helm-e2e.yaml, .github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
New CI setups, new directory for model cache etc.
Use random string for different namespace to avoid name conflict.
=> Use k8s-xeon cluster to run CI tasks

.github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
=> Use new lable for CI servers

.github/workflows/manual-helm-cd-workflow.yaml
=> Trigger helm test every Saturday (#900)

helm-charts/agentqna/gaudi-tgi-values.yaml, helm-charts/audioqna/gaudi-tgi-values.yaml, helm-charts/chatqna/cpu-tgi-values.yaml, helm-charts/chatqna/faqgen-gaudi-tgi-values.yaml, helm-charts/chatqna/faqgen-gaudi-values.yaml, helm-charts/chatqna/gaudi-tgi-values.yaml, helm-charts/chatqna/gaudi-values.yaml, helm-charts/chatqna/guardrails-gaudi-values.yaml, helm-charts/chatqna/nv-values.yaml, helm-charts/codegen/gaudi-tgi-values.yaml, helm-charts/codetrans/gaudi-tgi-values.yaml, helm-charts/common/agent/gaudi-tgi-values.yaml, helm-charts/common/agent/values.yaml, helm-charts/common/tei/gaudi-values.yaml, helm-charts/common/tei/values.yaml, helm-charts/common/teirerank/gaudi-values.yaml, helm-charts/common/teirerank/values.yaml, helm-charts/common/tgi/cpu-values.yaml, helm-charts/common/tgi/gaudi-values.yaml, helm-charts/common/tgi/nv-values.yaml, helm-charts/common/tgi/values.yaml, helm-charts/docsum/gaudi-tgi-values.yaml, helm-charts/searchqna/gaudi-values.yaml, helm-charts/visualqna/gaudi-tgi-values.yaml
Per discussion in #431, livenessProbe might cause restart of slow pods.
Per discussion of #431 and address comments of #931 
=> Remove the livenessProbe for tgi/tei/teirerank

helm-charts/valuefiles.yaml
=> Fix wrong name of faqgen value file

.github/workflows/manual-release-charts.yaml, .github/workflows/push-release-charts.yaml
The commonlib helm chart introduced extra level dependency.
Fix helm release script to handle multiple level dependency.
=> Update components dependency before packaging

.github/workflows/_helm-e2e.yaml, helm-charts/common/lvm-uservice/cpu-values.yaml
Remove the chart log file which cause issues on concurrent environment.
helm test exit code is equal to checking of "Phase: Failed", remove the redundant check.
Remove the -e to make sure dump pod logs at error.
Revert wrong modified copyright for lvm cpu-values.yaml
=> Clean up CI validate code for helm test

helm-charts/chatqna/Chart.yaml, helm-charts/chatqna/README.md, helm-charts/chatqna/cpu-milvus-values.yaml, helm-charts/chatqna/values.yaml, helm-charts/valuefiles.yaml
Enable milvus for chatqna VectorDB.
#839 
=> Enable milvus for chatqna VectorDB

.github/workflows/_helm-e2e.yaml
=> ci: dump pod logs when helm test failss

.github/workflows/_helm-e2e.yaml, helm-charts/common/nginx/templates/tests/test-pod.yaml
=> TEST - DO NOT MERGE

.github/workflows/_helm-e2e.yaml
ci: dump pod logs when helm test fails
`n/a`.
=> ci: dump pod logs when helm test fails

kubeai/README.md
Update README with the added model.
https://github.com/opea-project/GenAIInfra/issues/833
`n/a`
`n/a`
=> kubeai: README update

helm-charts/common/data-prep/README.md, helm-charts/common/data-prep/templates/deployment.yaml, helm-charts/common/data-prep/values.yaml, helm-charts/common/retriever-usvc/README.md, helm-charts/common/retriever-usvc/templates/deployment.yaml, helm-charts/common/retriever-usvc/values.yaml
Support airgap offline environment for data-prep and retriever-usvc helm chart.
Related to opea-project/GenAIComps#1488 and opea-project/GenAIComps#1491
=> dataprep/retriever: Support airgap offline environment

helm-charts/agentqna/cpu-values.yaml, helm-charts/agentqna/gaudi-values.yaml, helm-charts/audioqna/gaudi-values.yaml, helm-charts/chatqna/faqgen-gaudi-values.yaml, helm-charts/chatqna/gaudi-values.yaml, helm-charts/chatqna/guardrails-gaudi-values.yaml, helm-charts/codetrans/gaudi-values.yaml, helm-charts/common/agent/gaudi-values.yaml, helm-charts/common/llm-uservice/vllm-docsum-gaudi-values.yaml, helm-charts/common/llm-uservice/vllm-gaudi-values.yaml, helm-charts/common/vllm/gaudi-values.yaml, helm-charts/docsum/gaudi-values.yaml, kubeai/models/llama-3.1-8b-instruct-gaudi.yaml, kubeai/models/llama-3.3-70b-instruct-gaudi.yaml
=> Fix typo of vllm parameter

.github/workflows/manual-helm-cd-workflow.yaml, .github/workflows/pr-chart-e2e.yaml
- Add AMD rocm GPU support in CI.
- Simplify hardware choosing logic
`n/a`.
=> ci: add AMD rocm GPU support in CI

helm-charts/chatqna/Chart.yaml, helm-charts/chatqna/README.md, helm-charts/chatqna/guardrails-gaudi-values.yaml, helm-charts/chatqna/values.yaml
Use vllm for guradrails in chatqna.
Fixes #1004
=> chatqna: use vllm for guardrails

helm-charts/common/gpt-sovits/README.md, helm-charts/common/gpt-sovits/templates/configmap.yaml, helm-charts/common/gpt-sovits/templates/deployment.yaml, helm-charts/common/gpt-sovits/values.yaml
Adapt to the latest changes from opea-project/GenAIComps#1587
Fixes #1010
=> gpt-sovits: support model download and model cache

.github/workflows/push-release-charts.yaml, .github/workflows/scripts/get_chart_dependency.sh
Publish dependent charts on push event
`n/a`.
=> CI: publish dependent charts on push event

helm-charts/common/lvm-serve/gaudi-values.yaml
Adapt latest image name change from llava-gaudi to lvm-llava-gaudi.
`n/a`.
=> lvm-serve: lvm-llava gaudi image name change

cloud-service-provider/azure/aks/terraform/azure_main.tf
Remove unused resources (azurerm_storage_account, azurerm_storage_share) since they are not used and not needed. Storage account also requires extra privileges. 
`n/a`.
`n/a`
Manually tested on Azure.
=> terraform azure: remove unused resources

helm-charts/chatqna/README.md
Fixed accidental revert done by #949.
#1051
`n/a`
`n/a`
=> Fix README bug introdoced by #949

.github/workflows/_helm-e2e.yaml
Test of FinanceAgent require these keys: https://github.com/opea-project/GenAIInfra/pull/1063
=> Add API KEY for FinanceAgent

.github/workflows/_helm-e2e.yaml
THe vLLM warmup is good for performance but not related to functional tests. Remove the warmup to speedup ci tests.
=> Skip vLLM WARMUP for CI test on Gaudi nodes

kubeai/README.md
Co-authored-by: Malini Bhandaru <malini.bhandaru@intel.com>
=> kubeai/readme: improve nri optimization instructions

helm-charts/common/speecht5/templates/configmap.yaml, helm-charts/common/whisper/README.md, helm-charts/common/whisper/templates/configmap.yaml, helm-charts/common/whisper/templates/deployment.yaml, helm-charts/common/whisper/values.yaml
whisper: support air gapped environment.
Fix opea-project/GenAIComps#1487
=> whisper: support air gapped environment

helm-charts/chatqna/README.md
Remote Endpoint case miss HF Token for TEI and TEI Reranking.
[#1163 ]
NA
Test on customer cluster
=> README.md: set HF_TOKEN also in remote endpoint case
