opea-project/GenAIInfra

- .pre-commit-config.yaml
Enable --allow-multiple-documents in check-yaml of pre-commit-config
Enable --allow-multiple-documents in check-yaml of pre-commit-config because K8s manifest yaml files allows multiple documents.
> Enable --allow-multiple-documents in check-yaml of pre-commit-config

- .pre-commit-config.yaml
remove check-yaml and prettier from pre-commit-config for yaml checking 
Helm charts yamls have many special formats to support K8s deployment. Those cannot pass check-yaml defined in pre-commit-config. What's more, the `prettier` will format our charts yaml files which makes helm charts invalid. So we have to remove yaml checking from pre-commit-config. We will use helm charts validation CI to check helm charts yaml format.
> remove check-yaml and prettier from pre-commit-config for yaml checking

- helm-charts/codegen/.helmignore
- helm-charts/codegen/Chart.yaml
- helm-charts/codegen/README.md
- helm-charts/codegen/charts/tgi/.helmignore
- helm-charts/codegen/charts/tgi/Chart.yaml
- helm-charts/codegen/charts/tgi/README.md
- helm-charts/codegen/charts/tgi/templates/NOTES.txt
- helm-charts/codegen/charts/tgi/templates/_helpers.tpl
- helm-charts/codegen/charts/tgi/templates/deployment.yaml
- helm-charts/codegen/charts/tgi/templates/service.yaml
- helm-charts/codegen/charts/tgi/values.yaml
- helm-charts/codegen/templates/NOTES.txt
- helm-charts/codegen/templates/_helpers.tpl
- helm-charts/codegen/templates/deployment.yaml
- helm-charts/codegen/templates/service.yaml
- helm-charts/codegen/templates/tests/test-connection.yaml
- helm-charts/codegen/values.yaml
Two services in total, the codegen service is depending on tgi. Current tgi supports CPU only, will add Gaudi support later. You'll need a HuggingFace token in values.yaml
hf_token: "yourowntokenfromhuggingface"
Use "helm install codegen codegen" to deploy.
feature
Add CodeGen helm charts for Xeon
1. Modify the values.yaml hf_token with your huggingface API token
2.  helm install codegen codegen
3. curl http://test-codegen/v1/code_generation -X POST -H "Content-Type: application/json" -d '{"prompt": "def print_hello_world():", "max_new_tokens": 128, "stream": true}'
> Helm chart for CodeGen on Xeon

- microservices-connector/internal/controller/gmconnector_controller.go
Use the patch method in the GMC connector controller to react on the CR configuration change. With the reaction, the k8s will rolling update the according deployment
N/A
"k8s.io/utils/ptr"
- Tested on the k8s setup with GMC controller enabled, 
- All the GenAI micro services/deployments are ready, pipeline is working.
- Change the embedding or reranking configuration, checked the deployment, verify the rolling update happens, and pipeline is still functional.
- There is a demo video recording for it, but cannot be attached here due to the internal link accessibility.
>  reaction on CR changing

- helm-charts/codegen/charts/llm-uservice/charts/tgi/templates/deployment.yaml
- helm-charts/codegen/values.yaml
Allow user to run codegen with proxy settings.
This is to allow users to run codegen with proxy settings.
fix #79 
N/A
N/A
> helm-charts: Add proxy for codegen

- microservices-connector/Makefile
set DOCKER_REGISTRY before hand
- [x ] New feature (non-breaking change which adds new functionality)
N/A
test locally
> add docker build and push target for GMC

- .github/workflows/go-e2e.yaml
- .github/workflows/scripts/e2e/go_test.sh
Enable golang e2e test in CI
n/a
n/a
CI test
> Enable golang e2e test in CI

- .github/workflows/scripts/e2e/go_test.sh
- microservices-connector/config/gmcrouter/gmc-router.yaml
- microservices-connector/config/manager/gmc-manager.yaml
add gmc e2e test
`n/a`.
jq
we need to have jq installed on CI machine.
`sudo apt-get install jq`
e2e
> add gmc e2e

- .github/workflows/go-e2e.yaml
- .github/workflows/scripts/e2e/chart_test.sh
- .github/workflows/scripts/e2e/gmc_test.sh
- .github/workflows/scripts/e2e/manifest_test.sh
Change env OPEA_IMAGE_REPO to get consistent in xeon and gaudi CI test env.
In Gaudi test env, `$OPEA_IMAGE_REPO` is `<ip>:5000/`. In Xeon test env, `$OPEA_IMAGE_REPO` doesn't with `/`. In order to support both tests in Xeon and Gaudi, we have to keep them consistent.
n/a
CI Test
> Change env OPEA_IMAGE_REPO to get consistent in xeon and gaudi CI test env

- microservices-connector/config/samples/chatQnA_gaudi.yaml
- microservices-connector/internal/controller/gmconnector_controller.go
It's okay now for example of ChatQnA on both xeon and gaudi platform, and I also add the platform switcher on matedata label with label `gmc/platform`. `Test` section contains the deployment snapshots.
Moreover, I also validate the example by sending validated requests for them. 
https://github.com/opea-project/GenAIInfra/issues/118
`n/a`
**Xeon version:**
```
$ curl http://router-service.chatqa.svc.cluster.local:8080  \
>   -X POST \
>   -d '{"text":"What is the revenue of Nike in 2023?"}' \
>   -H 'Content-Type: application/json'
data: <br/>
data: An
data: swer
data: :
data: @#$In
data: @#$fiscal
data: @#$
data: 2
data: 0
data: 2
data: 3
data: ,
data: @#$N
data: I
data: KE
data: ,
data: @#$Inc
data: .
data: …
```
> Add the example of ChatQnA on gaudi node

- .github/workflows/scripts/e2e/gmc_test.sh
Fix a small bug in gmc e2e test.
If GMC meets with error during e2e tests, some namespace will not be created. Then the cleanup function will exist with error when deleting the not existed namespace, which will make the opea-system namespace remained in CI server.
closes issue #127 
n/a
CI test
> Fix a small bug in gmc e2e test

- .github/workflows/image-build-on-push.yaml
Enable image build on push for gmc
closes #137 
n/a
Tested in CI action : https://github.com/opea-project/GenAIInfra/actions/runs/9737177583
> Enable image build on push for gmc

- helm-charts/common/tgi/templates/deployment.yaml
New tgi 2.0.0 version will set MAX_INPUT_TOKENS to 4095 by default. This will cause tgi error. First set to 1024 as default, may make it configurable by user later.
‘n/a'
> Add MAX_INPUT_TOKENS to tgi

- helm-charts/common/tgi/Chart.yaml
- helm-charts/common/tgi/gaudi-values.yaml
- helm-charts/common/tgi/values.yaml
- helm-charts/update_dependency.sh
- manifests/common/tgi.yaml
- manifests/common/tgi_gaudi.yaml
- Upgrade tgi-gaudi to version 2.0.1 which works with habana sw stack 1.16.x.
- Upgrade tgi to version 2.1.0
- change default model to Intel/neural-chat-7b-v3-3
n/a
n/a
> Upgrade tgi version

- microservices-connector/config/authN-authZ/README.md
- microservices-connector/config/authN-authZ/chatQnA_authN_fakejwt.yaml
- microservices-connector/config/authN-authZ/chatQnA_authZ_fakejwt.yaml
- microservices-connector/usage_guide.md
Enable authN and authZ together with Istio and GMC using fake JWT token
- [ * ] New feature (non-breaking change which adds new functionality)
* create new folder under config to obtain authN, authZ configs
* add Istio authentication and authorization policies
* provide README for the task
Istio
> gmc: add authN & authZ support on fake JWT token

- .github/workflows/scripts/e2e/gmc_install.sh
- .github/workflows/scripts/e2e/gmc_xeon_test.sh
- microservices-connector/config/samples/chatQnA_gaudi.yaml
- microservices-connector/config/samples/chatQnA_xeon.yaml
- microservices-connector/config/samples/codegen_gaudi.yaml
- microservices-connector/config/samples/codegen_xeon.yaml
- microservices-connector/config/samples/codetrans_gaudi.yaml
- microservices-connector/config/samples/codetrans_xeon.yaml
- microservices-connector/config/samples/docsum_gaudi.yaml
- microservices-connector/config/samples/docsum_xeon.yaml
- microservices-connector/internal/controller/gmconnector_controller.go
- microservices-connector/internal/controller/gmconnector_controller_test.go
- microservices-connector/internal/controller/suite_test.go
This PR is a replica of #176 , since #176 has some difficulties to merge back because of the rebase issues. use this one to submit code.
this PR adopt the new manifests introduced by #173 and forget the old manifests. kept some code be comment out but not deleted in case the possible regression issue, after the old manifest deleted, these used code will be cleaned out.
this PR should've solved the issue  #138, and also be part of solution to the  #166 and #143
this PR also add support to WebRetriver service
#138, #166, #143
'n/a'
e2e regression tests passed
here is the log of searchqa result:
```
kefei@satg-opea-4node-1:~/repos/kfreez/GenAIInfra/microservices-connector$ kubectl exec …
```
> GMC: adopt new common/menifests

- microservices-connector/config/samples/searchQnA_gaudi.yaml
- microservices-connector/config/samples/searchQnA_xeon.yaml
Add new example of searchQnA on both xeon and gaudi.
`n/a`.
```sh
root@satg-opea-4node-1:/home/huailong# kubectl get svc -n searchqa     
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
embedding-svc       ClusterIP   172.21.58.179    <none>        6000/TCP   100m
llm-svc             ClusterIP   172.21.127.255   <none>        9000/TCP   99m
reranking-svc       ClusterIP   172.21.93.122    <none>        8000/TCP   99m
router-service      ClusterIP   172.21.129.137   <none>        8080/TCP   99m
tei-embedding-svc   ClusterIP   172.21.73.33     <none>        80/TCP     99m …
```
> Add new example of searchQnA on both xeon and gaudi

- microservices-connector/cmd/router/main.go
- microservices-connector/config/samples/chatQnA_switch_gaudi.yaml
- microservices-connector/config/samples/chatQnA_switch_xeon.yaml
1. Add necessary log output of router to debug
2. Add the ChatQnA example in **switch** mode via GMC for MI6 team, it's available on both Xeon and Gaudi
https://github.com/opea-project/GenAIInfra/issues/143
https://github.com/opea-project/GenAIInfra/issues/166
https://github.com/opea-project/GenAIInfra/issues/167
`n/a`.
@KfreeZ and I have validated these yaml files and we have showed the demo to @hteeyeoh, including the changes of `model-id` with values (large and small) and `embedding-model-id` with values(intel and llama)
> Support ChatQnA example in switch mode via GMC for MI6 team

- helm-charts/common/speecht5/templates/deployment.yaml
- helm-charts/common/whisper/templates/deployment.yaml
- manifests/common/speecht5.yaml
- manifests/common/speecht5_gaudi.yaml
- manifests/common/whisper.yaml
- manifests/common/whisper_gaudi.yaml
The current speecht5 and whisper doesn't allow runAsRoot if the /data directory is mounted from hostPath due to the permission issue inside the docker image.
`n/a`.
n/a.
> Disable runAsRoot for speecht5 and whisper

- helm-charts/chatqna/gaudi-values.yaml
- helm-charts/common/tei/gaudi-values.yaml
- manifests/common/tei_gaudi.yaml
Since upstream tei-gaudi has released its first official image, we use it instead of locally built opea/tei-gaudi.
`n/a`.
n/a
> Use upstream tei-gaudi image

- manifests/ChatQnA/README.md
- manifests/CodeGen/gaudi/README.md
- manifests/CodeGen/xeon/README.md
- manifests/CodeTrans/README.md
- manifests/DocSum/README.md
- manifests/README.md
- scripts/ray/README.md
markdown expects a first H1 (#) heading as the title for the document.
> doc: fix missing first heading in markdown files

- .github/workflows/chart-e2e.yaml
- .github/workflows/scripts/e2e/chart_test.sh
To improve the observability of CI jobs, add script to dump failed pod status and logs
Remove chart_test unused scripts
closes #154 
n/a
Show the status of not ready pods when deployment failed: https://github.com/opea-project/GenAIInfra/actions/runs/10091994310/job/27904720282#step:7:102
Show the log of failed pods when test failed: https://github.com/opea-project/GenAIInfra/actions/runs/10105854507/job/27947016154#step:8:151
> Add script to dump failed pod status and logs

- helm-charts/chatqna/README.md
- helm-charts/chatqna/nv-values.yaml
- helm-charts/common/tgi/nv-values.yaml
- manifests/common/tgi_nv.yaml
- manifests/update_manifests.sh
Add Nvidia GPU support for ChatQnA in helm-charts.
N/A
N/A
> Helm: Add Nvidia GPU support for ChatQnA

- helm-charts/common/data-prep/templates/deployment.yaml
- helm-charts/common/data-prep/templates/service.yaml
- helm-charts/common/data-prep/templates/tests/test-pod.yaml
- helm-charts/common/data-prep/values.yaml
- microservices-connector/config/manifests/data-prep.yaml
Update data-prep to use single port.
Issue #282.
n/a.
> helm: update data-prep to latest changes

- helm-charts/chatqna/gaudi-values.yaml
- helm-charts/codegen/gaudi-values.yaml
- helm-charts/codetrans/gaudi-values.yaml
- helm-charts/common/tei/gaudi-values.yaml
- helm-charts/common/tgi/gaudi-values.yaml
- helm-charts/common/tgi/templates/configmap.yaml
- helm-charts/common/tgi/templates/deployment.yaml
- helm-charts/common/tgi/values.yaml
- helm-charts/docsum/gaudi-values.yaml
- helm-charts/docsum/values.yaml
- microservices-connector/config/manifests/tgi_gaudi.yaml
This PR contains the following fix and enhancement
- Issue #286 
- Issue #287 
- allow user to config max_input_length & max_output_tokens
- #286
- #287
n/a.
> helm: fix tei/tgi/docsum

- helm-charts/common/speecht5/templates/deployment.yaml
- helm-charts/common/speecht5/values.yaml
- helm-charts/common/tei/templates/deployment.yaml
- helm-charts/common/tei/values.yaml
- helm-charts/common/teirerank/templates/deployment.yaml
- helm-charts/common/teirerank/values.yaml
- helm-charts/common/tgi/templates/deployment.yaml
- helm-charts/common/tgi/values.yaml
- helm-charts/common/whisper/templates/deployment.yaml
- helm-charts/common/whisper/values.yaml
Set modelUsePV to pvc name for model cache
modelUsePV support
#128 
Verified using nfs as PV backend.
Setup example:
PV:
apiVersion: v1
kind: PersistentVolume
metadata:
name: nfspv
spec:
capacity:
storage: 300Gi
volumeMode: Filesystem
accessModes:
- ReadWriteMany
persistentVolumeReclaimPolicy: Retain
storageClassName: nfs
nfs:
path: "/data/nfspv"
server: "192.168.0.184"
readOnly: false
PV Claim:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: model-volume
spec:
accessModes:
- ReadWriteMany
storageClassName: "nfs"
resources:
requests:
storage: 1Mi
Test example with whisper:
helm install whisper whisper --set global.modelUseHostPath="" --set …
> Enable using PV as model cache directory

- helm-charts/common/speecht5/templates/deployment.yaml
- helm-charts/common/speecht5/values.yaml
- helm-charts/common/tei/templates/deployment.yaml
- helm-charts/common/tei/values.yaml
- helm-charts/common/teirerank/templates/deployment.yaml
- helm-charts/common/teirerank/values.yaml
- helm-charts/common/tgi/templates/deployment.yaml
- helm-charts/common/tgi/values.yaml
- helm-charts/common/whisper/templates/deployment.yaml
- helm-charts/common/whisper/values.yaml
- helm-charts/update_manifests.sh
Set default value for model-volume to tmp volume.
Change modelUsePV to modelUsePVC as this is PVC.
Make modelUsePVC high priority than modelUseHostPath.
Minor fixes to PVC setting
#128 
Try with different settings and check the volume:
helm install tgi tgi --set global.HUGGINGFACEHUB_API_TOKEN=${HFTOKEN}
helm install tgi tgi --set global.HUGGINGFACEHUB_API_TOKEN=${HFTOKEN} --set global.modelUsePVC=model-volume
helm install tgi tgi --set global.HUGGINGFACEHUB_API_TOKEN=${HFTOKEN} --set global.modelUseHostPath=/mnt/models
helm install tgiboth tgi --set global.HUGGINGFACEHUB_API_TOKEN=${HFTOKEN} --set global.modelUseHostPath=/mnt/models --set global.modelUsePVC=model-volume
> Set model-volume default to tmp volume

- helm-charts/common/data-prep/templates/configmap.yaml
- helm-charts/common/llm-uservice/templates/configmap.yaml
- helm-charts/common/speecht5/templates/configmap.yaml
- helm-charts/common/tei/templates/configmap.yaml
- helm-charts/common/teirerank/templates/configmap.yaml
- helm-charts/common/tgi/templates/configmap.yaml
- helm-charts/common/whisper/templates/configmap.yaml
Support HF_ENDPOINT for use with huggingface mirrors
Please refer to this link for HF_ENDPOINT usage.
https://huggingface.co/docs/huggingface_hub/v0.13.2/en/package_reference/environment_variables#hfendpoint
Closed #299 
helm install whispernew common/whisper --set global.HF_ENDPOINT=https://hf-mirror.com
> Support HF_ENDPOINT

- microservices-connector/config/samples/chatQnA_nv.yaml
- microservices-connector/config/samples/chatQnA_switch_nv.yaml
- microservices-connector/internal/controller/gmconnector_controller.go
- microservices-connector/usage_guide.md
Enable NVIDIA GPU support for GMC, including sequence and switch modes. Note that switch mode may fail due to not enough GPU memory.
> GMC: Add GPU support for GMC.

- README.md
- helm-charts/README.md
Update helm chart readme, include how to use PersistentVolume as model cache.
Closed #128 
> Update helm chart readme

- helm-charts/chatqna/README.md
- helm-charts/chatqna/values.yaml
- helm-charts/codegen/README.md
- helm-charts/codegen/values.yaml
- helm-charts/codetrans/README.md
- helm-charts/codetrans/values.yaml
- helm-charts/docsum/README.md
- helm-charts/docsum/values.yaml
- helm-charts/update_genaiexamples.sh
The kubernetes manifests are generated from "helm template". Add the scripts to do that to avoid maintenance work.
> Add script to generate manifests from helm charts

- README.md
- kubernetes-addons/Intel-Gaudi-Base-Operator/README.md
Intel provides a base operator for the provisioning of Gaudi software. This README documents the whereabouts of this base operator.
This is the initial commit to introduce Intel Gaudi Base Operator to GenAIInfra.
For now, it is fine to follow the steps in the operator manual page. Should any further issues discovered, they should be addressed in this directory.
N/A
N/A
N/A
> Initial commit for Intel Gaudi Base Operator

- .github/workflows/scripts/e2e/gmc_xeon_test.sh
- helm-charts/common/retriever-usvc/templates/configmap.yaml
- helm-charts/common/retriever-usvc/values.yaml
- helm-charts/common/tgi/values.yaml
- microservices-connector/config/manifests/retriever-usvc.yaml
- microservices-connector/config/manifests/tgi.yaml
- microservices-connector/config/samples/chatQnA_switch_xeon.yaml
Due to bug opea-project/GenAIExamples#636, revert tgi xeon version to 2.2.0.
opea-project/GenAIExamples#636
n/a.
> tgi: revert xeon version to 2.2.0

- .github/workflows/_helm-e2e.yaml
- .github/workflows/manual-freeze-tag.yml
- .github/workflows/manual-helm-workflow
- .github/workflows/pr-chart-e2e.yaml
Add manual helm e2e test flow
n/a
n/a
n/a
> Add manual helm e2e test flow

- .github/workflows/scripts/e2e/gmc_xeon_test.sh
- .github/workflows/scripts/e2e/utils.sh
When wait_util_all_pod_ready is executed and there are pods being deleted, the wait_util_all_pod_ready count all the pods including Terminating pods and wait them to be ready, which could never happen.
Solution: exclude the terminating pods when collecting the pods names.
`n/a`.
`n/a`.
covered by CI/CD
> E2E: exclude terminating pods when wait_util_all_pod_ready

- helm-charts/common/data-prep/templates/configmap.yaml
- helm-charts/common/data-prep/values.yaml
- microservices-connector/config/manifests/data-prep.yaml
There are some config missing but required by get_file/delete_file API, add them for functional usage.
To fix #373
> helm-chart/data-prep: Add the missing config for dataprep-redis

- scripts/nvidia/README.md
* fix skipped heading levels
* fix misspellings, remove use of "please"
* fix inter-doc references to work with github.io rendering
> doc: fix headings, spelling, inter-doc references

- helm-charts/common/asr/templates/configmap.yaml
- helm-charts/common/asr/values.yaml
- helm-charts/common/data-prep/templates/configmap.yaml
- helm-charts/common/data-prep/values.yaml
- helm-charts/common/embedding-usvc/templates/configmap.yaml
- helm-charts/common/embedding-usvc/values.yaml
- helm-charts/common/llm-uservice/templates/configmap.yaml
- helm-charts/common/llm-uservice/values.yaml
- helm-charts/common/reranking-usvc/templates/configmap.yaml
- helm-charts/common/reranking-usvc/values.yaml
- helm-charts/common/retriever-usvc/templates/configmap.yaml
- helm-charts/common/retriever-usvc/values.yaml
- helm-charts/common/tts/templates/configmap.yaml
- helm-charts/common/tts/values.yaml
- helm-charts/common/web-retriever/templates/configmap.yaml
- helm-charts/common/web-retriever/values.yaml
- microservices-connector/config/manifests/asr.yaml
- microservices-connector/config/manifests/data-prep.yaml
- microservices-connector/config/manifests/docsum-llm-uservice.yaml
- microservices-connector/config/manifests/embedding-usvc.yaml
- microservices-connector/config/manifests/llm-uservice.yaml
- microservices-connector/config/manifests/reranking-usvc.yaml
- microservices-connector/config/manifests/retriever-usvc.yaml
- microservices-connector/config/manifests/tts.yaml
- microservices-connector/config/manifests/web-retriever.yaml
Logging is added in GenAIComps to print input/output, add it here for components debugging.
> helm-chart/common: Add logging config for service components

- microservices-connector/cmd/router/main_test.go
Add unit test for new function in GMC router.
`n/a`.
`n/a`.
This change includes the unit test for GMC router.
> Add unit test for new function in GMC router

- microservices-connector/internal/controller/gmconnector_controller.go
fix for #394 
**Root cause analysis:**
this issue is introduced by #383 , in this PR, I moved the deployment filters, but missed the 
```
CreateFunc: func(e event.CreateEvent) bool {
return false
}, DeleteFunc: func(e event.DeleteEvent) bool {
return false
},
```
without these two, the creation/deletion of the deployment triggers the reconcile, 
the sequence to hit this issue is like: delete GMC pipeline -> trigger deployment deletion ->trigger graph status update, but graph is already deleted ->panic.
**solution：**
- restore the create/delete filters
- add protection code
#394 
n/a
CI/CD cover the tests
> fix GMC crashes in e2e 

- helm-charts/chatqna/Chart.yaml
- helm-charts/chatqna/README.md
- helm-charts/chatqna/guardrails-gaudi-values.yaml
- helm-charts/chatqna/guardrails-values.yaml
- helm-charts/chatqna/templates/deployment.yaml
- helm-charts/chatqna/values.yaml
- helm-charts/common/guardrails-usvc/.helmignore
- helm-charts/common/guardrails-usvc/Chart.yaml
- helm-charts/common/guardrails-usvc/README.md
- helm-charts/common/guardrails-usvc/templates/_helpers.tpl
- helm-charts/common/guardrails-usvc/templates/configmap.yaml
- helm-charts/common/guardrails-usvc/templates/deployment.yaml
- helm-charts/common/guardrails-usvc/templates/service.yaml
- helm-charts/common/guardrails-usvc/templates/tests/test-pod.yaml
- helm-charts/common/guardrails-usvc/values.yaml
- helm-charts/common/tgi/templates/configmap.yaml
- helm-charts/update_genaiexamples.sh
- microservices-connector/config/manifests/guardrails-usvc.yaml
- microservices-connector/config/manifests/tgi.yaml
- microservices-connector/config/manifests/tgi_gaudi.yaml
- microservices-connector/config/manifests/tgi_nv.yaml
- Add component of guardrails llama_guard
- Add guardrails support in chatqna e2e workload
- Remove deprecated TRANSFORMERS_CACHE env in tgi because it results missing downloaded files on tgi-gaudi
Related to issue #348
n/a.
> helm: Add guardrails llama_guard support

- helm-charts/common/tgi/templates/deployment.yaml
- helm-charts/common/tgi/values.yaml
- microservices-connector/config/manifests/tgi.yaml
- microservices-connector/config/manifests/tgi_gaudi.yaml
- microservices-connector/config/manifests/tgi_nv.yaml
Add user configurable shm_size support.
Add interface for additional TGI cli parameters.
> Add TGI additional options

- helm-charts/chatqna/templates/deployment.yaml
- helm-charts/codegen/templates/deployment.yaml
- helm-charts/codetrans/templates/deployment.yaml
- helm-charts/common/asr/templates/deployment.yaml
- helm-charts/common/chatqna-ui/templates/deployment.yaml
- helm-charts/common/data-prep/templates/deployment.yaml
- helm-charts/common/embedding-usvc/templates/deployment.yaml
- helm-charts/common/guardrails-usvc/templates/deployment.yaml
- helm-charts/common/llm-uservice/templates/deployment.yaml
- helm-charts/common/redis-vector-db/templates/deployment.yaml
- helm-charts/common/reranking-usvc/templates/deployment.yaml
- helm-charts/common/retriever-usvc/templates/deployment.yaml
- helm-charts/common/speecht5/templates/deployment.yaml
- helm-charts/common/tei/templates/deployment.yaml
- helm-charts/common/teirerank/templates/deployment.yaml
- helm-charts/common/tgi/templates/deployment.yaml
- helm-charts/common/tts/templates/deployment.yaml
- helm-charts/common/vllm/templates/deployment.yaml
- helm-charts/common/web-retriever/templates/deployment.yaml
- helm-charts/common/whisper/templates/deployment.yaml
- helm-charts/docsum/templates/deployment.yaml
User can set evenly_distributed true to have the pods distribute evenly.
Closed #401 
> Add topologySpreadConstraints support

- .github/workflows/pr-go-unittests.yaml
- kubernetes-addons/memory-bandwidth-exporter/collector/class_collector_test.go
- kubernetes-addons/memory-bandwidth-exporter/collector/collector.go
- kubernetes-addons/memory-bandwidth-exporter/collector/collector_test.go
- kubernetes-addons/memory-bandwidth-exporter/collector/common_test.go
- kubernetes-addons/memory-bandwidth-exporter/collector/container_collector_test.go
- kubernetes-addons/memory-bandwidth-exporter/collector/node_collector_test.go
Add unit test for memory bandwidth exporter.
n/a
n/a
> Add unit test for memory bandwidth exporter.

- microservices-connector/config/samples/ChatQnA/chatQnA_switch_nv_OneCard.yaml
One TGI LLM microservice may take most of the GPU memory. Then another LLM may fail to launch when GPU memory is not enough if using GMC switch mode. TGI offers an environment parameter "--cuda-memory-fraction 0.5". It allows users to limit the amount of memory used by TGI.
See: https://github.com/huggingface/text-generation-inference/issues/673
This commit adds a CR for GMC switch if only having one NV GPU card.
https://github.com/opea-project/GenAIInfra/issues/323
> GMC: Add a CR for switch mode on one NV GPU card

- kubernetes-addons/memory-bandwidth-exporter/Dockerfile
- kubernetes-addons/memory-bandwidth-exporter/README.md
- kubernetes-addons/memory-bandwidth-exporter/config/manifests/memory-bandwidth-exporter.yaml
Expose options such as collector.interval of memory bandwidth exporter in k8s manifests and docker for user configuration.
n/a
n/a
n/a
n/a
> Expose options of memory bandwidth exporter in k8s manifests and docker for user configuration

- helm-charts/common/tgi/values.yaml
- microservices-connector/config/manifests/tgi.yaml
- microservices-connector/config/samples/ChatQnA/use_cases.md
Make all xeon tgi image version consistent.
`ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu` is intel cpu optimized tgi image, we need to use this one for all xeon platform.
`n/a`.
Related to [PR#851](https://github.com/opea-project/GenAIExamples/pull/851)
`n/a`
`n/a`
> Make all xeon tgi image version consistent

- helm-charts/chatqna/README.md
- helm-charts/chatqna/troubleshooting.md
Add a doc for chatqna troubleshooting on k8s
`n/a`.
`n/a`.
Run the command on k8s, which deploy chatqna.
> Add a doc for chatqna troubleshooting on k8s

- LEGAL_INFORMATION.md
- README.md
- helm-charts/HPA.md
- helm-charts/README.md
- helm-charts/chatqna/README.md
- helm-charts/chatqna/troubleshooting.md
- helm-charts/codegen/README.md
- helm-charts/common/asr/README.md
- helm-charts/common/data-prep/README.md
- helm-charts/common/retriever-usvc/README.md
- kubernetes-addons/Observability/README.md
- microservices-connector/config/samples/ChatQnA/use_cases.md
- microservices-connector/troubleshooting_guide.md
Cross-repo references using an URL that only has the folder name cause links in the github.io site to go to the github.com site.  Most of these uses want to link to the documentation (README.md) so add that where appropriate so links in the github.io site stay there.
> doc: fix missing references to README.md

- helm-charts/common/llm-uservice/templates/tests/test-pod.yaml
- helm-charts/common/llm-uservice/variant_docsum-values.yaml
- helm-charts/common/llm-uservice/variant_faqgen-values.yaml
- helm-charts/update_manifests.sh
- microservices-connector/config/manifests/faqgen-llm-uservice.yaml
- Add llm-faqgen-tgi support
- Add variant_xxx-values.yaml to support variants of the same chart
Related to issue #280.
> helm: Add llm-faqgen-tgi support

- helm-charts/chatqna/templates/custom-metrics-configmap.yaml
- helm-charts/codegen/gaudi-values.yaml
- helm-charts/codetrans/gaudi-values.yaml
- helm-charts/common/tei/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/teirerank/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/tgi/templates/horizontal-pod-autoscaler.yaml
- helm-charts/docsum/gaudi-values.yaml
Changes:
* Provide `accelDevice` Helm variables also in other charts using accelerated TGI / TEI
* Use different custom / HPA metrics depending on whether TGI / TEI is accelerated
Queue size metric is a bit better for scaling TGI Gaudi instances than the one used for Xeon scaling, and queries for it are simpler.  HPA rule updates act also as examples on use of different HPA algorithm types (`Value` vs. `AverageValue`).
`n/a`.
`n/a`.
Did manual testing of HPA scaling of 1-4 TGI Gaudi instances (4 = maxReplicas value), using different TGI-provided metrics, and batch sizes.
PS. none of the TGI / TEI metrics seem that good for scaling, their values mostly indicate just whether given component is stressed, not _how_ slow the resulting (e.g. ChatQnA) queries are.   Meaning that HPA scaling …
> Support alternative metrics on accelerated TGI / TEI instances

- helm-charts/common/chathistory-usvc/.helmignore
- helm-charts/common/chathistory-usvc/Chart.yaml
- helm-charts/common/chathistory-usvc/README.md
- helm-charts/common/chathistory-usvc/templates/_helpers.tpl
- helm-charts/common/chathistory-usvc/templates/configmap.yaml
- helm-charts/common/chathistory-usvc/templates/deployment.yaml
- helm-charts/common/chathistory-usvc/templates/service.yaml
- helm-charts/common/chathistory-usvc/templates/tests/test-pod.yaml
- helm-charts/common/chathistory-usvc/values.yaml
- helm-charts/common/mongodb/.helmignore
- helm-charts/common/mongodb/Chart.yaml
- helm-charts/common/mongodb/README.md
- helm-charts/common/mongodb/templates/_helpers.tpl
- helm-charts/common/mongodb/templates/deployment.yaml
- helm-charts/common/mongodb/templates/service.yaml
- helm-charts/common/mongodb/templates/tests/test-pod.yaml
- helm-charts/common/mongodb/values.yaml
- helm-charts/common/prompt-usvc/.helmignore
- helm-charts/common/prompt-usvc/Chart.yaml
- helm-charts/common/prompt-usvc/README.md
- helm-charts/common/prompt-usvc/templates/_helpers.tpl
- helm-charts/common/prompt-usvc/templates/configmap.yaml
- helm-charts/common/prompt-usvc/templates/deployment.yaml
- helm-charts/common/prompt-usvc/templates/service.yaml
- helm-charts/common/prompt-usvc/templates/tests/test-pod.yaml
- helm-charts/common/prompt-usvc/values.yaml
ChatHistory/PromptRegistry and mongodb.
Add helm charts for 3 components
#281 
Local build opea/promptregistry-mongo and opea/chathistory-mongo-server.
helm install and helm test
> Add helm chart for 3 components

- helm-charts/chatqna/gaudi-values.yaml
- helm-charts/chatqna/guardrails-gaudi-values.yaml
- helm-charts/chatqna/nv-values.yaml
- helm-charts/codegen/gaudi-values.yaml
- helm-charts/codetrans/gaudi-values.yaml
- helm-charts/common/tei/gaudi-values.yaml
- helm-charts/common/tei/values.yaml
- helm-charts/common/teirerank/values.yaml
- helm-charts/common/tgi/gaudi-values.yaml
- helm-charts/common/tgi/nv-values.yaml
- helm-charts/common/tgi/values.yaml
- helm-charts/docsum/gaudi-values.yaml
- microservices-connector/config/manifests/tei.yaml
- microservices-connector/config/manifests/tei_gaudi.yaml
- microservices-connector/config/manifests/teirerank.yaml
- microservices-connector/config/manifests/tgi.yaml
- microservices-connector/config/manifests/tgi_gaudi.yaml
- microservices-connector/config/manifests/tgi_nv.yaml
Sync the mismatch between helm chart and GMC manifests introduced by PR #386
`n/a`.
> helm/manifest: Sync HPA related K8S probe settings

- .github/workflows/_helm-e2e.yaml
- .github/workflows/pr-chart-e2e.yaml
- .pre-commit-config.yaml
- helm-charts/chatqna/Chart.yaml
- helm-charts/chatqna/templates/deployment.yaml
Change the helm chart follow this commit
https://github.com/opea-project/GenAIExamples/commit/619d9410477408dcc51bc0058851e9e8f59185a2
CI changes first step
#471 
Closed #466 
> Implement the nowrapper version chatqna

- .gitignore
- helm-charts/common/data-prep/Chart.yaml
- helm-charts/common/data-prep/README.md
- helm-charts/common/data-prep/ci-values.yaml
- helm-charts/common/data-prep/milvus-values.yaml
- helm-charts/common/data-prep/templates/configmap.yaml
- helm-charts/common/data-prep/templates/deployment.yaml
- helm-charts/common/data-prep/templates/service.yaml
- helm-charts/common/data-prep/templates/tests/test-pod.yaml
- helm-charts/common/data-prep/values.yaml
- helm-charts/common/retriever-usvc/Chart.yaml
- helm-charts/common/retriever-usvc/README.md
- helm-charts/common/retriever-usvc/ci-values.yaml
- helm-charts/common/retriever-usvc/milvus-values.yaml
- helm-charts/common/retriever-usvc/templates/configmap.yaml
- helm-charts/common/retriever-usvc/templates/deployment.yaml
- helm-charts/common/retriever-usvc/templates/service.yaml
- helm-charts/common/retriever-usvc/values.yaml
Add milvus support for data-prep and retriever-usvc.
Use "helm install" with -f milvus-values.yaml
We don't provide milvus deployment helm chart, just reuse the one officially released with current version.
https://artifacthub.io/packages/helm/milvus/milvus
helm install dataprep data-prep -f data-prep/milvus-values.yaml
> Add milvus support for data-prep

- helm-charts/update_manifests.sh
- microservices-connector/config/manifests/chathistory-usvc.yaml
- microservices-connector/config/manifests/mongodb.yaml
- microservices-connector/config/manifests/prompt-usvc.yaml
- microservices-connector/config/manifests/vllm.yaml
- microservices-connector/config/manifests/vllm_gaudi.yaml
Add manifests for vllm/chathistory/prompt/mongodb
Skip ci-*values.yaml in update script.
> Add manifests for new components

- .github/workflows/scripts/codeScan/bandit.sh
- kubernetes-addons/memory-bandwidth-exporter/Dockerfile
- microservices-connector/Dockerfile.manager
- microservices-connector/Dockerfile.router
- This PR updates base containers to `golang:1.23` wherever appropriate
- Adds `no-cache-dir` to all `pip` installs
- Ensures `--no-install-recommends --fix-missing` are used everywhere along with `apt-get` installs
N/A
- [N/A] Bug fix (non-breaking change which fixes an issue)
- [N/A] New feature (non-breaking change which adds new functionality)
- [N/A] Breaking change (fix or feature that would break existing design and interface)
None
This is not adding any new infra but CI's needs to pass prior to merge.
> Minor enhancements to Dockerfiles

- cloud-service-provider/aws/eks/README.MD
- cloud-service-provider/aws/eks/eks-efs-csi-pvc.yaml
- cloud-service-provider/aws/eks/main.tf
- cloud-service-provider/aws/eks/opea-chatqna.tfvars
- cloud-service-provider/aws/eks/outputs.tf
- cloud-service-provider/aws/eks/terraform.tf
- cloud-service-provider/aws/eks/variables.tf
Add AWS/EKS terraform deployment for OPEA applications. This PR add support for ChatQnA.
Followup PRs add more cloud providers and OPEA applications.
https://github.com/opea-project/GenAIExamples/issues/427
https://github.com/opea-project/GenAIExamples/issues/551
https://github.com/opea-project/GenAIExamples/issues/550
https://github.com/opea-project/GenAIExamples/issues/549
https://github.com/opea-project/GenAIExamples/issues/510
None
None
> terraform: add AWS/EKS deployment for ChatQnA

- helm-charts/chatqna/gaudi-values.yaml
- helm-charts/common/teirerank/gaudi-values.yaml
- helm-charts/common/teirerank/templates/configmap.yaml
Accelerate also `teirerank` with Gaudi, not just `tei`.
When reranking is used, it does not make sense (performance-wise) to accelerate just tei, as reranking is a larger bottleneck.
#486
`n/a`.
Manually checked the ChatQnA throughput.
> ChatQnA: accelerate also teirerank with Gaudi

- helm-charts/chatqna/gaudi-values.yaml
- helm-charts/chatqna/guardrails-gaudi-values.yaml
- helm-charts/common/tei/gaudi-values.yaml
- microservices-connector/config/manifests/tei_gaudi.yaml
- microservices-connector/config/samples/ChatQnA/use_cases.md
Upgrade tei-gaudi version to 1.5.0.
#454
> Upgrade tei-gaudi version to 1.5.0

- .github/workflows/scripts/e2e/utils.sh
Turn off bash errexit during wait for pod in GMC test so that CI script can dump pod status.
`n/a`.
n/a.
n/a.
> CI: turn off bash errexit during wait for pod in GMC test

- helm-charts/common/lvm-uservice/.helmignore
- helm-charts/common/lvm-uservice/Chart.yaml
- helm-charts/common/lvm-uservice/README.md
- helm-charts/common/lvm-uservice/ci-values.yaml
- helm-charts/common/lvm-uservice/templates/_helpers.tpl
- helm-charts/common/lvm-uservice/templates/configmap.yaml
- helm-charts/common/lvm-uservice/templates/deployment.yaml
- helm-charts/common/lvm-uservice/templates/service.yaml
- helm-charts/common/lvm-uservice/templates/servicemonitor.yaml
- helm-charts/common/lvm-uservice/templates/tests/test-pod.yaml
- helm-charts/common/lvm-uservice/values.yaml
- helm-charts/visualqna/.helmignore
- helm-charts/visualqna/Chart.yaml
- helm-charts/visualqna/README.md
- helm-charts/visualqna/ci-gaudi-values.yaml
- helm-charts/visualqna/ci-values.yaml
- helm-charts/visualqna/gaudi-values.yaml
- helm-charts/visualqna/templates/_helpers.tpl
- helm-charts/visualqna/templates/deployment.yaml
- helm-charts/visualqna/templates/nginx-deployment.yaml
- helm-charts/visualqna/templates/service.yaml
- helm-charts/visualqna/templates/tests/test-pod.yaml
- helm-charts/visualqna/values.yaml
Add visualqna and the dependent lvm-uservice helm charts.
Helm chart support for VisualQnA
https://github.com/opea-project/GenAIExamples/tree/main/VisualQnA
#504 
For both Gaudi and Xeon cases,
helm dependency update
helm install vqna visualqna
helm test vqna
> Add helm chart for VisualQnA example

- helm-charts/common/llm-uservice/templates/tests/test-pod.yaml
- helm-charts/faqgen/templates/tests/test-pod.yaml
Limit max_tokens to 17 save test time and avoid sporadic timout on busy CI nodes on cpu case.
`n/a`.
n/a.
CI.
> Limit max_tokens to save test time

- .github/workflows/pr-chart-validate.yaml
- helm-charts/common/gpt-sovits/.helmignore
- helm-charts/common/gpt-sovits/Chart.yaml
- helm-charts/common/gpt-sovits/README.md
- helm-charts/common/gpt-sovits/ci-values.yaml
- helm-charts/common/gpt-sovits/templates/_helpers.tpl
- helm-charts/common/gpt-sovits/templates/configmap.yaml
- helm-charts/common/gpt-sovits/templates/deployment.yaml
- helm-charts/common/gpt-sovits/templates/service.yaml
- helm-charts/common/gpt-sovits/templates/tests/test-pod.yaml
- helm-charts/common/gpt-sovits/values.yaml
- Add the helm chart for gpt-sovits which is used by AudioQnA multilang example.
- Enable helm lint for GenAIComps charts.
#504
> helm-charts: Add gpt-sovits support

- helm-charts/audioqna/README.md
- helm-charts/audioqna/templates/servicemonitor.yaml
- helm-charts/audioqna/values.yaml
- helm-charts/codegen/README.md
- helm-charts/codegen/templates/servicemonitor.yaml
- helm-charts/codegen/values.yaml
- helm-charts/codetrans/README.md
- helm-charts/codetrans/templates/servicemonitor.yaml
- helm-charts/codetrans/values.yaml
- helm-charts/docsum/README.md
- helm-charts/docsum/templates/servicemonitor.yaml
- helm-charts/docsum/values.yaml
- helm-charts/faqgen/README.md
- helm-charts/faqgen/templates/servicemonitor.yaml
- helm-charts/faqgen/values.yaml
- helm-charts/visualqna/README.md
- helm-charts/visualqna/templates/servicemonitor.yaml
Background: All applications already use Gateway => HttpService class instance, so they all already provide Prometheus metrics end point.   And https://github.com/opea-project/GenAIComps/pull/845 adds more service specific Prometheus metrics to ServiceOrchestrator, which is also used by the all the applications.
This PR adds `ServiceMonitor`s to all the remaining applications, so that their metrics are also visible in Prometheus, Grafana etc, similarly to ChatQnA (PR #488).
This includes fix to VisualQnA, which README and values file incorrectly contained the monitoring items, but had no ServiceMonitor.
`n/a`.
`n/a`. 
Manually verified that rest of the applications `Service` files are identical to ChatQnA …
> Add monitoring (ServiceMonitors) for rest of OPEA applications

- helm-charts/chatqna/gaudi-values.yaml
- helm-charts/chatqna/guardrails-gaudi-values.yaml
- helm-charts/common/tei/gaudi-values.yaml
- helm-charts/common/tei/templates/configmap.yaml
- helm-charts/common/tei/values.yaml
- helm-charts/common/teirerank/gaudi-values.yaml
- helm-charts/common/teirerank/templates/configmap.yaml
- helm-charts/common/teirerank/values.yaml
- helm-charts/common/tgi/gaudi-values.yaml
- helm-charts/common/tgi/templates/configmap.yaml
- helm-charts/common/tgi/values.yaml
Align parameters with docker compose version
Fixes #499, Fixes #487, Fixes #530 
Helm install
> Align HPU parameters with docker compose

- helm-charts/agentqna/.helmignore
- helm-charts/agentqna/Chart.yaml
- helm-charts/agentqna/README.md
- helm-charts/agentqna/gaudi-values.yaml
- helm-charts/agentqna/templates/_helpers.tpl
- helm-charts/agentqna/templates/crag.yaml
- helm-charts/agentqna/templates/docretriever.yaml
- helm-charts/agentqna/templates/tests/test-pod.yaml
- helm-charts/agentqna/values.yaml
- helm-charts/common/agent/.helmignore
- helm-charts/common/agent/Chart.yaml
- helm-charts/common/agent/README.md
- helm-charts/common/agent/ci-gaudi-values.yaml
- helm-charts/common/agent/gaudi-values.yaml
- helm-charts/common/agent/templates/_helpers.tpl
- helm-charts/common/agent/templates/configmap.yaml
- helm-charts/common/agent/templates/deployment.yaml
- helm-charts/common/agent/templates/service.yaml
- helm-charts/common/agent/templates/servicemonitor.yaml
- helm-charts/common/agent/templates/tests/test-pod.yaml
- helm-charts/common/agent/values.yaml
- helm-charts/common/tgi/templates/configmap.yaml
Add helm chart for AgentQnA and agent component.
Fixes #428, Fixes opea-project/GenAIExamples#755
Tested on Gaudi
> Helm Chart for AgentQnA

- helm-charts/HPA.md
- helm-charts/monitoring.md
- kubernetes-addons/Observability/README.md
This includes following documentation improvements:
* Removes obsolete "Gotchas" section from monitoring doc
* Links monitoring and observability docs + adds missing spaces to latter
* Improves HPA doc CPU notes
`n/a`.
`n/a`.
`n/a`.  (doc update, CI + review is enough)
> Monitoring, Observability and HPA doc improvements

- kubernetes-addons/Observability/opea-apps/opea-scaling.json
- kubernetes-addons/Observability/update-dashboards.sh
Adds Grafana dashboard for monitoring OPEA application scaling:
* How many of the application and its TGI + TEI pods are created, ready and in use
* How many requests they are processing (min and max across all replicats)
* How many failures they are reporting (sum across replicas)
And a helper script for installing dashboard k8s `configMap`s for Grafana.
Unlike earlier ChatQnA dashboard, this handles multiple OPEA application having same names but being in separate namespaces.  User selects namespace and then the OPEA application from that.  If cluster has only one running, Dashboard will default to that.
(Therefore it does not make sense to install dashboard with application specific Helm charts, as it can cover all apps that use TGI for LLM, i.e. most of them.)
`n/a`.
`n/a`.
Manual …
> Add Grafana dashboard for monitoring OPEA application scaling in k8s

- .github/workflows/manual-freeze-tag.yaml
- .github/workflows/manual-helm-cd-workflow.yaml
- .github/workflows/manual-release-charts.yaml
* manual-freeze-tag.yaml to run on release branch, modify version and tags
* manual-helm-cd-workflow.yaml to trigger tests
* manual-release-charts.yaml to release the helm charts to public repo
#561 
> Add github workflows to release helm chart

- helm-charts/README.md
- helm-charts/agentqna/README.md
- helm-charts/audioqna/Chart.yaml
- helm-charts/common/agent/README.md
- helm-charts/common/gpt-sovits/Chart.yaml
- microservices-connector/config/manifests/gpt-sovits.yaml
Also fix audioqna version to keep consistent with others. The version number will be upgraded on release branch first.
Using ghcr to release helm charts.
#559 
> README pointing to ghcr.io package

- microservices-connector/api/v1alpha3/validating_webhook.go
- microservices-connector/cmd/router/main.go
- microservices-connector/config/samples/ChatQnA/chatQnA_dataprep_xeon_with_ui.yaml
- microservices-connector/internal/controller/gmconnector_controller.go
* add ui handler in GMC router logic
* add sample config file for chatqna with conversation ui
`n/a`.
> gmc: include ui as part of pipeline

- helm-charts/common/llm-uservice/ci-vllm-gaudi-values.yaml
- helm-charts/common/vllm/gaudi-values.yaml
- helm-charts/common/vllm/templates/configmap.yaml
- microservices-connector/config/manifests/vllm_gaudi.yaml
Rename image name XXX-hpu to XXX-gaudi.
> Rename image name XXX-hpu to XXX-gaudi

- .github/workflows/scripts/e2e/gmc_gaudi_test.sh
- .github/workflows/scripts/e2e/gmc_xeon_test.sh
- .github/workflows/scripts/e2e/manifest_gaudi_test.sh
- .github/workflows/scripts/e2e/manifest_xeon_test.sh
- helm-charts/common/ui/templates/configmap.yaml
- helm-charts/docsum/Chart.yaml
- helm-charts/docsum/README.md
- helm-charts/docsum/templates/m2t.yaml
- helm-charts/docsum/templates/tests/test-pod.yaml
- helm-charts/docsum/templates/v2a.yaml
- helm-charts/docsum/values.yaml
- microservices-connector/config/manifests/docsum_svelte-ui.yaml
Added multimedia2text and video2audio service
Fixes #579 
> Update docsum according to docker compose changes

- cloud-service-provider/aws/eks/terraform/README.MD
> Fix the helm repo links

- helm-charts/audioqna/README.md
> Fix audioqna readme for cached MODELDIR

- .github/workflows/_helm-e2e.yaml
- .github/workflows/manual-freeze-tag.yaml
- .github/workflows/manual-helm-cd-workflow.yaml
- .github/workflows/manual-release-charts.yaml
- helm-charts/chatqna/values.yaml
- helm-charts/visualqna/values.yaml
* Use official name and email for CICD
* Enable GH action to trigger test with released image
* Unify quotation marks usage for repository value
> Github action changes

- helm-charts/README.md
> Add 4 new examples to README

- kubernetes-addons/Observability/README.md
- kubernetes-addons/Observability/update-dashboards.sh
Changes based on feedback from testing by @poussa.
Script updates:
* Fix shellcheck warnings
* Improve dashboard JSON validity checks
- Grafana will generate 'uid' on configMap load if it is missing
* Make sure dashboard configMap name matches k8s rules
* Restart Grafana to make sure it picks up the configMap updates
README updates:
* Document what the script does and what implications `configMap` usage for dashboards has
`n/a`.
`n/a`.
Manual testing
> Grafana script + README improvements

- kubernetes-addons/Observability/README.md
- kubernetes-addons/Observability/update-dashboards.sh
Single `configMap` label is enough, and Grafana does not need to be restarted, one just needs to wait enough for it to check+process new `configMap`s & do Grafana page reload.
=> Updated script + README accordingly.
Grafana restart had following usability issues:
* It breaks Grafana instance `kubectl port-forward`ing for everybody using it at the same time
* If dashboard does not have an UID, i.e. restarted Grafana generates a new UID, URL for such dashboards change
`n/a`.
Tested script manually with new and updated dashboard JSONs.
> Improve dashboard upload script

- README.md
Add links to terraform modules so they can be linked to OPEA documentation.
`n/a`.
`n/a`.
Manual testing: doc looks okay and link works.
> README: add links to terraform docs

- helm-charts/common/guardrails-usvc/README.md
- helm-charts/common/speecht5/templates/configmap.yaml
- helm-charts/common/speecht5/templates/deployment.yaml
- helm-charts/common/speecht5/values.yaml
- helm-charts/common/tei/templates/configmap.yaml
- helm-charts/common/tei/templates/deployment.yaml
- helm-charts/common/tei/values.yaml
- helm-charts/common/teirerank/templates/configmap.yaml
- helm-charts/common/teirerank/templates/deployment.yaml
- helm-charts/common/teirerank/values.yaml
- helm-charts/common/tgi/README.md
- helm-charts/common/tgi/templates/deployment.yaml
- helm-charts/common/tgi/values.yaml
- helm-charts/common/vllm/templates/deployment.yaml
- helm-charts/common/whisper/templates/configmap.yaml
- helm-charts/common/whisper/templates/deployment.yaml
- helm-charts/common/whisper/values.yaml
Add initContainer to download model to avoid the permission conflict issue of the .locks directory in the host `modeUseHostPath` path, when sharing the host model directory between different services. 
`n/a`.
> Add initContainer to download model

- helm-charts/audioqna/Chart.yaml
- helm-charts/audioqna/templates/nginx-deployment.yaml
- helm-charts/audioqna/values.yaml
- helm-charts/common/ui/ci-variant_audioqna_svelte-values.yaml
- helm-charts/common/ui/variant_audioqna_svelte-values.yaml
Add audioqna UI support in helm chart.
Fixes #626.
> Helm: Add audioqna UI support

- helm-charts/common/speecht5/templates/deployment.yaml
- helm-charts/common/tei/templates/deployment.yaml
- helm-charts/common/teirerank/templates/deployment.yaml
- helm-charts/common/tgi/templates/configmap.yaml
- helm-charts/common/tgi/templates/deployment.yaml
- helm-charts/common/vllm/templates/deployment.yaml
- helm-charts/common/whisper/templates/deployment.yaml
Upgrade huggingface-hub to version 0.26.5 when downloading models, due to the existing `huggingface/downloader:0.17.3` image doesn't acknowledge the HF_TOKEN correctly.
Loose the tgi securityContext to allow running with multi shard.
Fixes #641 
Fixes #639
> Fix model-downloader and tgi in multi shard case

- helm-charts/common/data-prep/README.md
- helm-charts/common/data-prep/templates/servicemonitor.yaml
- helm-charts/common/data-prep/values.yaml
- helm-charts/docsum/templates/m2t.yaml
- helm-charts/docsum/templates/v2a.yaml
ChatQnA + DocSum had few components which provide metrics endpoint, but did not have Prometheus `serviceMonitor`s for (optional) collection of those metrics.  This adds them.
`n/a`.
`n/a`.
Manual testing with `latest` images.
These components use `MicroService` class, so they provide metrics both from that and underlying HTTP service.  
However, because they don't process any tokens with `MicroService`, its metrics are always zero.  I'll try to come up with some way to skip exporting them from `MicroService` in "GenAIComps".
> Add monitoring for rest of ChatQnA + DocSum components

- helm-charts/audioqna/Chart.yaml
- helm-charts/audioqna/gaudi-values.yaml
- helm-charts/audioqna/templates/deployment.yaml
- helm-charts/common/speecht5/values.yaml
- helm-charts/common/whisper/values.yaml
Adapt to latest changes in audioqna, whisper, speecht5.
Fixes #660.
> audioqna: reduce microservice numbers

- .github/workflows/check-online-doc-build.yml
Pin to run on ubuntu 22.04 since docc CI doesn't support python 3.12 in ubuntu 24.04.
`n/a`.
> Unblock doc CI

- helm-charts/common/llm-uservice/.helmignore
- helm-charts/common/llm-uservice/README.md
- helm-charts/common/llm-uservice/ci-docsum-values.yaml
- helm-charts/common/llm-uservice/ci-faqgen-values.yaml
- helm-charts/common/llm-uservice/ci-vllm-docsum-gaudi-values.yaml
- helm-charts/common/llm-uservice/templates/configmap.yaml
- helm-charts/common/llm-uservice/templates/deployment.yaml
- helm-charts/common/llm-uservice/templates/tests/test-pod.yaml
- helm-charts/common/llm-uservice/values.yaml
- helm-charts/common/llm-uservice/variant_docsum-values.yaml
- helm-charts/common/llm-uservice/variant_faqgen-values.yaml
Adapt to latest changes in llm microservice famliy.
Fixes #691
> Adapt to latest changes in llm microservice famliy

- helm-charts/common/tgi/values.yaml
This is the first PR for #643 , the plan is to get tgi change reviewed and merged, then doing the same for other charts.(To avoid too many CI testing)
Tried several requests settings(With small values) and it doesn't have obvious impact on the resource usage.
So set this should be good enough.
cpu: 100m
memory: 128Mi
It's performance tuning's task to set more reasonable resource limit/requests according to different scenarios.
#643 
> Add minimal resource requests for tgi

- helm-charts/agentqna/values.yaml
- helm-charts/common/agent/README.md
- helm-charts/common/agent/templates/configmap.yaml
- helm-charts/common/agent/templates/tests/test-pod.yaml
- helm-charts/common/agent/values.yaml
Use stream to follow OpenAI's API.
Rename the image name from agent-langchain to agent.
closed #668 #670 
> Adapt latest changes for agentqna

- helm-charts/docsum/Chart.yaml
- helm-charts/docsum/README.md
- helm-charts/docsum/ci-gaudi-tgi-values.yaml
- helm-charts/docsum/ci-gaudi-values.yaml
- helm-charts/docsum/ci-gaudi-vllm-values.yaml
- helm-charts/docsum/gaudi-tgi-values.yaml
- helm-charts/docsum/gaudi-vllm-values.yaml
- helm-charts/docsum/values.yaml
This was split from Helm vLLM support added in https://github.com/opea-project/GenAIInfra/pull/610. It adds  vLLM support to _DocSum_ Helm chart.
(Similarly to how it's already done for _ChatQnA_ app + _Agent_ component, there are `tgi.enabled` & `vllm.enabled` flags for selecting which LLM will be used.)
`opea/llm-docsum-vllm:latest` image is currently missing from CI & DockerHub registries:
https://github.com/opea-project/GenAIComps/issues/961
(Although corresponding `opea/llm-docsum-tgi:latest` image for TGI, and `opea/llm-vllm:latest` vLLM text-generation images already exist.)
Manual testing with `opea/llm-docsum-vllm:latest` image built locally.
> Add vLLM support to DocSum Helm chart

- helm-charts/codegen/gaudi-values.yaml
- helm-charts/codegen/values.yaml
- helm-charts/codetrans/gaudi-values.yaml
- helm-charts/codetrans/values.yaml
- helm-charts/common/guardrails-usvc/README.md
- helm-charts/common/guardrails-usvc/templates/configmap.yaml
- helm-charts/common/guardrails-usvc/templates/deployment.yaml
- helm-charts/common/guardrails-usvc/values.yaml
- helm-charts/common/llm-uservice/templates/tests/test-pod.yaml
- helm-charts/common/tgi/templates/configmap.yaml
- helm-charts/faqgen/gaudi-values.yaml
- helm-charts/faqgen/values.yaml
- helm-charts/visualqna/gaudi-values.yaml
- helm-charts/visualqna/values.yaml
Adapt latest changes to the following helm chart:
- codegen
- codetrans
- faqgen
- visualqna
- guadrails-usvc
- llm-uservice
- Fix #688
- Fix #689
- Fix #669
- Fix #666
- Fix #717
> Refactor codegen codetrans faqgen visualqna and guardrails-usvc

- helm-charts/common/retriever-usvc/README.md
- helm-charts/common/retriever-usvc/milvus-values.yaml
- helm-charts/common/retriever-usvc/templates/configmap.yaml
- helm-charts/common/retriever-usvc/templates/deployment.yaml
- helm-charts/common/retriever-usvc/values.yaml
Adapt latest changes for retriever.
Fixes #707.
> Adapt latest changes for retriever

- kubernetes-addons/istio/README.md
- kubernetes-addons/istio/helmfile.yaml
- kubernetes-addons/istio/istio-gateway-and-virtual-service.yaml
- kubernetes-addons/istio/istio-gateway-ca-and-cert.yaml
- kubernetes-addons/istio/istio-mtls-strict.yaml
Istio service mesh provides many features including
- mTLS between Kubernetes pods
- TLS connection to Kubernetes ingress
This PR provides an example how to enable the above two Istio features with OPEA applications. 
#548
'n/a'
Manually tested.
> Add Istio mTLS and ingress gateway with TLS example

- helm-charts/agentqna/Chart.yaml
- helm-charts/agentqna/gaudi-values.yaml
- helm-charts/agentqna/templates/tests/test-pod.yaml
- helm-charts/agentqna/values.yaml
- helm-charts/agentqna/vllm-gaudi-values.yaml
- helm-charts/common/agent/templates/configmap.yaml
- helm-charts/common/agent/templates/deployment.yaml
- helm-charts/common/agent/templates/tests/test-pod.yaml
- helm-charts/common/vllm/templates/configmap.yaml
Add sql-agent.
Add vllm as llm engine.
More parameters added to support latest changes.
> Add sql-agent to AgentQnA

- helm-charts/common/data-prep/README.md
- helm-charts/common/data-prep/milvus-values.yaml
- helm-charts/common/data-prep/templates/configmap.yaml
- helm-charts/common/data-prep/templates/deployment.yaml
- helm-charts/common/data-prep/templates/tests/test-pod.yaml
- helm-charts/common/data-prep/values.yaml
Adapt latest changes for data-prep.
Fixes #730
> Adapt latest changes for data-prep

- cloud-service-provider/azure/aks/terraform/README.md
- cloud-service-provider/azure/aks/terraform/azure_main.tf
- cloud-service-provider/azure/aks/terraform/opea-chatqna.tfvars
- cloud-service-provider/azure/aks/terraform/outputs.tf
- cloud-service-provider/azure/aks/terraform/variables.tf
Infosys contribution to OPEA.
Added CosmosDB and App Insights to the terraform on Azure.
NA
None
Tested terraforms on Azure platform.
> [Feature] Added automated provisioning of CosmosDB and App Insights for OPEA applications  - Infosys

- helm-charts/HPA.md
- helm-charts/chatqna/hpa-values.yaml
- helm-charts/monitoring.md
* HPA requires metrics, so enable `monitoring` automatically in `hpa-values.yaml`
* Minor updates to docs
`n/a`.
`n/a`.
`n/a`.
Verified that the Helm generated manifests with the updated `hpa-values.yaml` are identical to ones generated earlier with `--set global.monitoring=true` option.
> HPA enabling usability improvement

- .github/workflows/pr-chart-validate.yaml
Exclude library charts from chart-lint since they don't have values files.
`n/a`.
> CI: exclude library charts from chart-lint

- .github/workflows/pr-chart-e2e.yaml
- .github/workflows/push-release-charts.yaml
Filter files that are not helm charts
Fix the failure of update helm charts
https://github.com/opea-project/GenAIInfra/actions/runs/13257577897/job/37006999398
> Fix wrong detection of helm-chart name in CI

- .github/workflows/push-release-charts.yaml
(Replacement for accidentally closed #814, that could not be re-opened.)
Improve release chart identification for pushing, by:
* Separating common functionality to its own function
* Making exclusion matches more explicit:
- Exclude all files directly in `helm-charts/`
- Exclude non-helm subdirs, instead of files in them (including new `assets/` subdir for doc screenshots)
* Fixes
Fixes following issues:
* Current exclude patterns are missing the PNG files in the (new) `assets/` directory
* Current `*.md` `*.sh` patterns are **not** file name extension matches, as `*` matches any string and `.` matches _any_ character (they work just by luck, because currently none of the other files include "md" nor "sh" in their names...)
* Current rules ignore Chart doc updates, but users can query …
> Improve release chart identification for pushing

- helm-charts/chatqna/hpa-values.yaml
- helm-charts/common/lvm-serve/values.yaml
- helm-charts/common/mm-embedding/values.yaml
- helm-charts/common/nginx/values.yaml
- helm-charts/common/ollama/values.yaml
- helm-charts/common/tei/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/tei/values.yaml
- helm-charts/common/teirerank/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/teirerank/values.yaml
- helm-charts/common/text2image/values.yaml
- helm-charts/common/tgi/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/tgi/values.yaml
- helm-charts/common/vllm/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/vllm/values.yaml
* Add minReplicas option for all autoscalable components
* Use same explanation/comments for all of them
* Remove statements about the required service scale down termination handling
- It's relevant for the Helm template, but not for Chart usage
`n/a`.
`n/a`.
Just CI, as changes are trivial.
> Add minReplicas option for rest of autoscalable components

- helm-charts/common/llm-uservice/README.md
- helm-charts/common/llm-uservice/templates/configmap.yaml
- helm-charts/common/llm-uservice/values.yaml
- helm-charts/common/llm-uservice/variant_textgen-bedrock-values.yaml
Provide support for using Amazon Bedrock with llm-textgen through environment variable configuration.
n/a
n/a
Performed `helm install llm-uservice llm-uservice -f llm-uservice/variant_textgen-bedrock-values.yaml` and confirmed that inference is still functional. Performed installation using both AWS access keys and using EKS Pod Identity to provide AWS credentials to container.
> LLM TextGen Bedrock Support

- .github/workflows/manual-release-charts.yaml
Some of the folders in helm-charts are not helm charts, skip them at release if there is no Chart.yaml file.
See the failure of https://github.com/opea-project/GenAIInfra/actions/runs/13643535093/job/38138154683
> Skip non helm chart directory for release

- helm-charts/common/dashboard/templates/configmap-metrics.yaml
App dashboard improvements:
* Dashboard menus get their info from pending request metric instead of first token one
* Request & token rate panels use more specific units instead of generic count/sec one
* Enable dashboard refresh (at 30s interval)
Dashboard did not list anything unless requests were using stream mode.  Using pending request metric fixes that.
`n/a`.
Checked manually that Dashboard works fine.
> App dashboard improvements

- helm-charts/audioqna/templates/deployment.yaml
The commit https://github.com/opea-project/GenAIExamples/commit/2dfcfa0436e8e44c536fa721e97142707f50d5b8 updated the LLM model param with real model name from env, we have to export the correct env from values file. 
Current helm chart only supports TGI, so this PR only exports env from TGI model. 
Fixes #849 
N/A
Install helm chart from [source code](https://github.com/haoruan/opea-project-GenAIInfra/tree/main/helm-charts/audioqna)
> add LLM_MODEL_ID env to audioqna to set the correct model

- helm-charts/agentqna/gaudi-values.yaml
- helm-charts/chatqna/cpu-tgi-values.yaml
- helm-charts/chatqna/gaudi-vllm-values.yaml
- helm-charts/chatqna/guardrails-gaudi-values.yaml
- helm-charts/common/agent/gaudi-values.yaml
- helm-charts/common/llm-uservice/vllm-docsum-gaudi-values.yaml
- helm-charts/common/llm-uservice/vllm-gaudi-values.yaml
- helm-charts/common/vllm/gaudi-values.yaml
- helm-charts/common/vllm/templates/configmap.yaml
- helm-charts/common/vllm/templates/deployment.yaml
- helm-charts/common/vllm/values.yaml
- helm-charts/docsum/gaudi-vllm-values.yaml
1. Add securityContext settings for image of opea/vllm and opea/vllm-gaudi.
2. Increase cpu limits settings for tei/teirerank since ingesting pdf files requires more cpu times to avoid request failure due to
embedding/reranking service unresponsiveness.
Related to issue #815
> vllm: Add securityContxt settings

- helm-charts/agentqna/gaudi-values.yaml
- helm-charts/chatqna/gaudi-vllm-values.yaml
- helm-charts/chatqna/guardrails-gaudi-values.yaml
- helm-charts/common/agent/gaudi-values.yaml
- helm-charts/common/llm-uservice/vllm-docsum-gaudi-values.yaml
- helm-charts/common/llm-uservice/vllm-gaudi-values.yaml
- helm-charts/common/vllm/gaudi-values.yaml
- helm-charts/common/vllm/templates/configmap.yaml
- helm-charts/docsum/gaudi-vllm-values.yaml
Both latest images of `opea/vllm` and `opea/vllm-gaudi` needs some special settings to run as non-root.
`n/a`.
> vllm: support to run as non-root

- helm-charts/codegen/Chart.yaml
- helm-charts/codegen/README.md
- helm-charts/codegen/cpu-tgi-values.yaml
- helm-charts/codegen/gaudi-tgi-values.yaml
- helm-charts/codegen/gaudi-values.yaml
- helm-charts/codegen/templates/tests/test-pod.yaml
- helm-charts/codegen/values.yaml
- helm-charts/valuefiles.yaml
codegen: add vLLM as default inference engine
Fixes #869 
CI for xeon env, manually for gaudi env.
> codegen: add vLLM as default inference engine

- helm-charts/codetrans/Chart.yaml
- helm-charts/codetrans/README.md
- helm-charts/codetrans/cpu-tgi-values.yaml
- helm-charts/codetrans/gaudi-tgi-values.yaml
- helm-charts/codetrans/gaudi-values.yaml
- helm-charts/codetrans/values.yaml
- helm-charts/valuefiles.yaml
codetrans: add vLLM as default inference engine
Fixes #858
CI on xeon, manually on Gaudi
> codetrans: add vLLM as default inference engine

- helm-charts/common/lvm-uservice/Chart.yaml
- helm-charts/common/lvm-uservice/README.md
- helm-charts/common/lvm-uservice/cpu-llava-values.yaml
- helm-charts/common/lvm-uservice/cpu-tgi-values.yaml
- helm-charts/common/lvm-uservice/cpu-values.yaml
- helm-charts/common/lvm-uservice/gaudi-values.yaml
- helm-charts/common/lvm-uservice/templates/configmap.yaml
- helm-charts/common/lvm-uservice/values.yaml
- helm-charts/common/vllm/templates/configmap.yaml
- helm-charts/valuefiles.yaml
- helm-charts/visualqna/Chart.yaml
- helm-charts/visualqna/README.md
- helm-charts/visualqna/cpu-tgi-values.yaml
- helm-charts/visualqna/gaudi-tgi-values.yaml
- helm-charts/visualqna/gaudi-values.yaml
- helm-charts/visualqna/values.yaml
Enable vLLM for lvm-uservice.
Enable vLLM as default LVM backend for VisualQnA.
Update READMEs.
Add PT_HPUGRAPH_DISABLE_TENSOR_CACHE option for vllm, which is necessary to serve LVM models.
#880 
#877 
Helm install with all available values.yaml files.
> Add vLLM backend for visualqna

- helm-charts/codegen/templates/tests/test-pod.yaml
To avoid CI timeout in busy environment, we need to put limit on max_tokens.
`n/a`.
> codegen: limit max output token in test case

- cloud-service-provider/aws/eks/terraform/main.tf
- cloud-service-provider/aws/eks/terraform/opea-chatqna.tfvars
- cloud-service-provider/aws/eks/terraform/terraform.tf
- cloud-service-provider/aws/eks/terraform/variables.tf
This PR updates the AWS provider version in the EKS terraform configuration from 5.49.0 to 5.79.0. The changes include: - Updating AWS provider version constraint to ~> 5.79.0 - Adding comments about version constraint options - Fixing a newline issue in terraform.tf - Updating instance type to i7ie.12xlarge (corrected case) in opea-chatqna.tfvars - Setting AWS region to us-east-1 in both variables.tf and opea-chatqna.tfvars The update ensures compatibility with the latest AWS provider features and improvements.
> Update AWS provider version to 5.79.0 in EKS terraform configuration

- cloud-service-provider/aws/eks/terraform/main.tf
Typo fix
Typo fixes for ":" to "=" in the Terraform template. This error caused the example to fail because it couldn't correctly create the PVC, and the pods, depending on that, were failing to launch.
- [ x] Bug fix (non-breaking change which fixes an issue)
> Typo fix on main.tf

- kubeai/models/llama-3.3-70b-instruct-gaudi.yaml
Add llama-3.3-70b-instruct model for Gaudi with resource profile and vLLM args/env to KubeAI.
(https://github.com/opea-project/GenAIInfra/issues/833)
`n/a`
Manually tested with [llmperf](https://github.com/ray-project/llmperf).
> kubeai: add llama-3.3-70b-instruct model for Gaudi

- helm-charts/common/lvm-uservice/values.yaml
New opea/vllm image doesn‘t have the chat template included. Same change as https://github.com/opea-project/GenAIExamples/pull/1831
Fix the helm chart part of component lvm https://github.com/opea-project/GenAIComps/issues/1589
> Remove chat-template

- helm-charts/chatqna/Chart.yaml
- helm-charts/chatqna/README.md
- helm-charts/chatqna/cpu-ollama-values.yaml
- helm-charts/chatqna/templates/deployment.yaml
- helm-charts/chatqna/values.yaml
This integrates the existing ollama component into the ChatQnA RAG so it can be used with with helm/k8s. I'm working on a blog post for Canonical (the company behind Ubuntu) highlighting OPEA that will make use of this feature.
n/a
- [x ] New feature (non-breaking change which adds new functionality)
None
I successfully tested the following on my Dell XPS13 laptop (32 GiB RAM) running Ubuntu 24.04 with Canonical Kubernetes:
```bash
helm install chatqna chatqna --set global.HUGGINGFACEHUB_API_TOKEN=${HFTOKEN} --set global.modelUseHostPath=${MODELDIR} -f chatqna/cpu-ollama-values.yaml
```
```bash
helm install chatqna chatqna --set global.HUGGINGFACEHUB_API_TOKEN=${HFTOKEN} --set …
```
> chatqna: integrate ollama llm k8s support

- .github/workflows/_helm-e2e.yaml
- .github/workflows/manual-freeze-tag.yaml
- .github/workflows/manual-release-charts.yaml
- .github/workflows/pr-chart-validate.yaml
- .github/workflows/pr-path-detection.yml
- .github/workflows/push-release-charts.yaml
- helm-charts/README.md
- helm-charts/TDX.md
- helm-charts/audioqna/README.md
- helm-charts/chatqna/README.md
- helm-charts/codegen/README.md
- helm-charts/codetrans/README.md
- helm-charts/docsum/README.md
- helm-charts/scripts/check_values.sh
- helm-charts/scripts/update_dependency.sh
- helm-charts/scripts/update_genaiexamples.sh
- helm-charts/scripts/update_manifests.sh
- helm-charts/searchqna/README.md
- helm-charts/txt2img/README.md
- helm-charts/visualqna/README.md
Move current `helm-charts/*.sh` scripts to new `helm-charts/scripts/` subdir.  Remove variable name inconsistency for that dir.
Done in preparation for future PRs that add more Helm chart helper scripts.
`n/a`.
`n/a`.
Manually verified that all paths to these scripts have been updated accordingly:
```
scripts=$(ls helm-charts/scripts/)
for i in $scripts; do echo $i:; git grep $i; echo; done
```
Couple of docs in other repos reference `update_dependency.sh`, but that's all.  Those can be updated after this PR is in.
GenAIExamples:
```
DocSum/kubernetes/helm/README.md:./update_dependency.sh
DocSum/kubernetes/helm/README.md:./update_dependency.sh
```
docs:
```
tutorial/ChatQnA/deploy/k8s_getting_started.md:- A script called **./update_dependency.sh** is provided which is used to update chart …
```
> Move Helm chart helper scripts to scripts/ subdir

- .github/workflows/pr-path-detection.yml
Take into account that PR's repo fork can have different name than this repo.  And check URLs only once.
`n/a`.
`n/a`.
Docs repo CI, this is same fix as needed for https://github.com/opea-project/docs/pull/378.
> Fix CI URL checker paths for forked repos

- kubeai/README.md
Fixed a typo in example command in README.md
- Typo fix in documentation
> Fixed a typo in example command in README.md

- helm-charts/chatqna/README.md
Update first README clause to indicate that some of the subservices are conditional, and fix another ChatQnA README regression introduced by #949.
`n/a`.
`n/a`.
CI.
> Fix ChatQnA README regression

- kubeai/README.md
- kubeai/models/llama-3.1-8b-instruct-gaudi.yaml
- kubeai/models/llama-3.3-70b-instruct-gaudi.yaml
- kubeai/opea-values.yaml
KubeAI updates:
* Autoscale 8b Gaudi model
* Change 70b Gaudi model to scale-from-zero, to avoid idle pods reserving 4 devices
* Add example nodeSelectors
* Update README / fix typos in it
`n/a`.
`n/a`.
Manual testing for scaling / changes.
> Improve KubeAI autoscaling support

- helm-charts/common/llm-uservice/README.md
- helm-charts/common/llm-uservice/templates/configmap.yaml
- helm-charts/common/llm-uservice/templates/deployment.yaml
- helm-charts/common/llm-uservice/values.yaml
- helm-charts/common/llm-uservice/vllm-docsum-gaudi-values.yaml
- helm-charts/common/llm-uservice/vllm-gaudi-values.yaml
- Support air gapped environment
- Temporary workaround for GenAIComps issue #1719
`n/a`.
> llm-uservice: Support air gapped environment

- kubeai/README.md
Document a preferred setup of the Balloons Policy from the NRI Plugins project.
> kubeai: document usage of NRI plugins for performance optimization

- helm-charts/common/data-prep/README.md
- helm-charts/common/data-prep/templates/configmap.yaml
- helm-charts/common/data-prep/templates/deployment.yaml
- helm-charts/common/data-prep/values.yaml
dataprep: support air gapped environment.
> dataprep: Support air gapped environment

- helm-charts/agentqna/values.yaml
- helm-charts/chatqna/hpa-values.yaml
- helm-charts/chatqna/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/dashboard/templates/configmap-metrics.yaml
When rate of requests increases and backend inference engines get scaled, megaservice becomes performance bottleneck (as its query processing is single threaded), so that needs to be scaled too.  This is the case already after scaling to few Gaudi vLLM instances with the default 8b Llama model.
Other changes:
* Add Megaservice scaling info to OPEA application dashboard
* Remove unused HPA setting from AgentQnA
`n/a`.
(Fixes scaling performance bottleneck.)
`n/a`.
Tested manually.
> Autoscaling for ChatQnA megaservice

- helm-charts/HPA.md
- helm-charts/chatqna/hpa-values.yaml
- helm-charts/chatqna/templates/custom-metrics-configmap.yaml
- helm-charts/common/dashboard/templates/configmap-metrics.yaml
- helm-charts/common/tei/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/tei/values.yaml
- helm-charts/common/teirerank/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/teirerank/values.yaml
- helm-charts/common/tgi/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/tgi/values.yaml
- helm-charts/common/vllm/templates/horizontal-pod-autoscaler.yaml
- helm-charts/common/vllm/values.yaml
* Fix OPEA app metrics Grafana dashboad query for TGI  next tokens rate
* Disable vLLM warmup when HPA is used, otherwise vLLM startup takes too long
* Use `.Series`, `.GroupBy` and `.LabelMatchers` to simplify Prometheus-adapter custom metric rules
* Document autoscaling metric considerations, currently used metrics, and pros & cons of other metrics
* Change vLLM to be scaled by same metric as what KubeAI uses (active requests) + add Helm variable for its threshold
* Drop request latency metric for TGI/TEI scaling, it's too dependent on input & output token counts to be useful
- CPU scaling uses now same metric as accelerated scaling
* Add Helm variable for TGI/TEI queue size scaling threshold, with separate CPU and acceleration thresholds
`n/a`.
List the type of change like below. …
> Rework HPA scaling metrics and their configuration

- .github/workflows/_helm-e2e.yaml
This PR extends the CI scripts to support testing with external LLM endpoints. The changes add configuration for external LLM services in the Helm E2E workflow, allowing charts with external-llm-values.yaml files to be tested against external LLM providers. The implementation includes environment variable mapping for different chart types (ChatQnA, DocSum, CodeGen etc) and supports configurable LLM server hosts, ports, models, and API keys.
n/a
No new 3rd party dependencies introduced.
The changes extend existing Helm E2E tests to support external LLM endpoint testing. Charts with external-llm-values.yaml files will now be tested with the configured …
> Extend CI scripts to test for external LLM endpoints

- helm-charts/common/data-prep/README.md
- helm-charts/common/gpt-sovits/README.md
- helm-charts/common/llm-uservice/README.md
- helm-charts/common/speecht5/README.md
Remove extra "..." continuations from docs.
(Single "..." continuation is slightly more readable than multiple of them, and consistent with other docs.)
`n/a`.
`n/a`.
CI.
> Remove extra "..." continuations from docs

- helm-charts/chatqna/README.md
- helm-charts/codegen/README.md
Fix #993 values file names to match README.
`n/a`.
`n/a`.
CI.
> Fix READMEs to match (external LLM) values file names

- helm-charts/chatqna/faqgen-gaudi-tgi-values.yaml
- helm-charts/chatqna/faqgen-gaudi-values.yaml
- helm-charts/chatqna/gaudi-tgi-values.yaml
- helm-charts/chatqna/gaudi-values.yaml
- helm-charts/chatqna/guardrails-gaudi-values.yaml
- helm-charts/common/tei/gaudi-values.yaml
- helm-charts/common/teirerank/gaudi-values.yaml
- helm-charts/searchqna/gaudi-values.yaml
Upgrade ghcr.io/huggingface/tei-gaudi:1.5.0 into
ghcr.io/huggingface/text-embeddings-inference:hpu-1.7.
Fixes #1157
> Change tei/teirerank image on gaudi

- helm-charts/chatqna/README.md
- helm-charts/chatqna/templates/deployment.yaml
- helm-charts/chatqna/values.yaml
- helm-charts/chatqna/variant_external-llm-values.yaml
- helm-charts/codegen/README.md
- helm-charts/codegen/templates/deployment.yaml
- helm-charts/codegen/values.yaml
- helm-charts/codegen/variant_external-llm-values.yaml
Improve/shorten/fix Helm variable names [1]:
- Consistent Helm variable naming: LLM_SERVICE/LLM_SERVER -> LLM_SERVER
- Drop misleading/redundant _IP suffix: LLM_SERVER_HOST_IP -> LLM_SERVER_HOST
Add:
- Examples on using OPEA KubeAI installation as external LLM
- LLM_SERVER_PORT setting to everywhere LLM_SERVER_HOST is set
- Comment about NGINX and data-prep / *-ui enabling dependency
- Missing HF_TOKEN settings to external LLM usage examples
- Missing Ollama disabling
See also PR https://github.com/opea-project/GenAIInfra/pull/1167 for more general external inferencing support.
[1] Helm variables do not need to duplicate naming problems in OPEA applications: https://github.com/opea-project/GenAIExamples/issues/2143.
Fixes incorrect external LLM variable name in CodeGen value file, missing …
> External LLM endpoint usage improvements + fixes
